-- Ajusta os tamanhos das colunas utilizadas na importação SIGTAP
-- O script é idempotente: só altera colunas que estiverem menores que o layout
-- Execute sempre conectado ao banco correto e preferencialmente após um backup.

SET AUTODDL OFF;
SET TERM ^^ ;

/* ---------------------
   TB_RUBRICA
--------------------- */
EXECUTE BLOCK AS
DECLARE VARIABLE CURRENT_LENGTH INTEGER;
BEGIN
    SELECT F.RDB$FIELD_LENGTH
      FROM RDB$RELATION_FIELDS RF
      JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
     WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_RUBRICA'
       AND TRIM(RF.RDB$FIELD_NAME) = 'CO_RUBRICA'
      INTO :CURRENT_LENGTH;

    IF (COALESCE(:CURRENT_LENGTH, 0) < 6) THEN
        EXECUTE STATEMENT 'ALTER TABLE TB_RUBRICA ALTER CO_RUBRICA TYPE VARCHAR(6)';
END^^

EXECUTE BLOCK AS
DECLARE VARIABLE CURRENT_LENGTH INTEGER;
BEGIN
    SELECT F.RDB$FIELD_LENGTH
      FROM RDB$RELATION_FIELDS RF
      JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
     WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_RUBRICA'
       AND TRIM(RF.RDB$FIELD_NAME) = 'NO_RUBRICA'
      INTO :CURRENT_LENGTH;

    IF (COALESCE(:CURRENT_LENGTH, 0) < 100) THEN
        EXECUTE STATEMENT 'ALTER TABLE TB_RUBRICA ALTER NO_RUBRICA TYPE VARCHAR(100)';
END^^

EXECUTE BLOCK AS
DECLARE VARIABLE CURRENT_LENGTH INTEGER;
BEGIN
    SELECT F.RDB$FIELD_LENGTH
      FROM RDB$RELATION_FIELDS RF
      JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
     WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_RUBRICA'
       AND TRIM(RF.RDB$FIELD_NAME) = 'DT_COMPETENCIA'
      INTO :CURRENT_LENGTH;

    IF (COALESCE(:CURRENT_LENGTH, 0) < 6) THEN
        EXECUTE STATEMENT 'ALTER TABLE TB_RUBRICA ALTER DT_COMPETENCIA TYPE CHAR(6)';
END^^

/* ---------------------
   TB_CID
--------------------- */
EXECUTE BLOCK AS
DECLARE VARIABLE CURRENT_LENGTH INTEGER;
BEGIN
    SELECT F.RDB$FIELD_LENGTH
      FROM RDB$RELATION_FIELDS RF
      JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
     WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_CID'
       AND TRIM(RF.RDB$FIELD_NAME) = 'CO_CID'
      INTO :CURRENT_LENGTH;

    IF (COALESCE(:CURRENT_LENGTH, 0) < 4) THEN
        EXECUTE STATEMENT 'ALTER TABLE TB_CID ALTER CO_CID TYPE VARCHAR(4)';
END^^

EXECUTE BLOCK AS
DECLARE VARIABLE CURRENT_LENGTH INTEGER;
BEGIN
    SELECT F.RDB$FIELD_LENGTH
      FROM RDB$RELATION_FIELDS RF
      JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
     WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_CID'
       AND TRIM(RF.RDB$FIELD_NAME) = 'TP_ESTADIO'
      INTO :CURRENT_LENGTH;

    IF (COALESCE(:CURRENT_LENGTH, 0) < 1) THEN
        EXECUTE STATEMENT 'ALTER TABLE TB_CID ALTER TP_ESTADIO TYPE CHAR(1)';
END^^

SET TERM ; ^^
COMMIT;
SET AUTODDL ON;

