-- Criar índice único para prevenir duplicatas em RL_PROCEDIMENTO_OCUPACAO (CBO)
-- Este índice garante que não haverá duplicatas de CO_PROCEDIMENTO + CO_OCUPACAO + DT_COMPETENCIA

-- 1. Verificar se o índice já existe
SELECT 
    TRIM(I.RDB$INDEX_NAME) AS INDEX_NAME,
    TRIM(R.RDB$RELATION_NAME) AS TABELA,
    LIST(TRIM(ISG.RDB$FIELD_NAME), ', ') AS CAMPOS
FROM RDB$INDICES I
INNER JOIN RDB$RELATION_CONSTRAINTS RC ON I.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
INNER JOIN RDB$RELATIONS R ON RC.RDB$RELATION_NAME = R.RDB$RELATION_NAME
INNER JOIN RDB$INDEX_SEGMENTS ISG ON I.RDB$INDEX_NAME = ISG.RDB$INDEX_NAME
WHERE TRIM(R.RDB$RELATION_NAME) = 'RL_PROCEDIMENTO_OCUPACAO'
  AND TRIM(I.RDB$INDEX_NAME) = 'IDX_RL_POCUP_UNIQUE'
GROUP BY I.RDB$INDEX_NAME, R.RDB$RELATION_NAME;

-- 2. Verificar se há duplicatas antes de criar o índice
SELECT 
    CO_OCUPACAO,
    CO_PROCEDIMENTO,
    DT_COMPETENCIA,
    COUNT(*) AS TOTAL_DUPLICATAS
FROM RL_PROCEDIMENTO_OCUPACAO
GROUP BY CO_OCUPACAO, CO_PROCEDIMENTO, DT_COMPETENCIA
HAVING COUNT(*) > 1;

-- 3. Criar índice único (execute apenas se não houver duplicatas)
-- ATENÇÃO: Este comando falhará se houver duplicatas existentes!
-- Limpe as duplicatas primeiro usando limpar_duplicatas_cbo_preservar_maiusculas.sql

CREATE UNIQUE INDEX IDX_RL_POCUP_UNIQUE 
ON RL_PROCEDIMENTO_OCUPACAO (CO_PROCEDIMENTO, CO_OCUPACAO, DT_COMPETENCIA);

-- 4. Verificar se o índice foi criado com sucesso
SELECT 
    TRIM(I.RDB$INDEX_NAME) AS INDEX_NAME,
    TRIM(R.RDB$RELATION_NAME) AS TABELA,
    LIST(TRIM(ISG.RDB$FIELD_NAME), ', ') AS CAMPOS,
    CASE WHEN RC.RDB$CONSTRAINT_TYPE = 'UNIQUE' THEN 'UNIQUE' ELSE 'NORMAL' END AS TIPO
FROM RDB$INDICES I
INNER JOIN RDB$RELATION_CONSTRAINTS RC ON I.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
INNER JOIN RDB$RELATIONS R ON RC.RDB$RELATION_NAME = R.RDB$RELATION_NAME
INNER JOIN RDB$INDEX_SEGMENTS ISG ON I.RDB$INDEX_NAME = ISG.RDB$INDEX_NAME
WHERE TRIM(R.RDB$RELATION_NAME) = 'RL_PROCEDIMENTO_OCUPACAO'
  AND TRIM(I.RDB$INDEX_NAME) = 'IDX_RL_POCUP_UNIQUE'
GROUP BY I.RDB$INDEX_NAME, R.RDB$RELATION_NAME, RC.RDB$CONSTRAINT_TYPE;

