-- Script: Criar Índices para Otimização (VERSÃO SIMPLIFICADA)
-- Objetivo: Criar índices compostos para melhorar performance
-- ATENÇÃO: Execute apenas se os índices não existirem

-- Indice 1: Para BuscarCID10RelacionadosAsync
-- Query: WHERE pc.CO_PROCEDIMENTO = @coProcedimento AND pc.DT_COMPETENCIA = @competencia
CREATE INDEX IDX_RL_PCID_PROC_COMP ON RL_PROCEDIMENTO_CID 
    (CO_PROCEDIMENTO, DT_COMPETENCIA);

-- Indice 2: Para BuscarPorCIDAsync  
-- Query: WHERE pc.DT_COMPETENCIA = @competencia AND pc.CO_CID = @cid
CREATE INDEX IDX_RL_PCID_CID_COMP ON RL_PROCEDIMENTO_CID 
    (CO_CID, DT_COMPETENCIA);

-- Verificar indices criados
SELECT 
    TRIM(I.RDB$INDEX_NAME) AS INDICE,
    TRIM(I.RDB$RELATION_NAME) AS TABELA,
    TRIM(S.RDB$FIELD_NAME) AS CAMPO,
    S.RDB$FIELD_POSITION AS POSICAO
FROM RDB$INDICES I
JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME = 'RL_PROCEDIMENTO_CID'
  AND I.RDB$SYSTEM_FLAG = 0
  AND I.RDB$INDEX_NAME IN ('IDX_RL_PCID_PROC_COMP', 'IDX_RL_PCID_CID_COMP')
ORDER BY I.RDB$INDEX_NAME, S.RDB$FIELD_POSITION;

