-- Script para DELETAR duplicatas de CID10
-- Estratégia: Mantém apenas o registro com menor INDICE de cada grupo
-- (CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA)

-- 1. VERIFICAR total de duplicatas ANTES
SELECT 
    'ANTES - Total duplicatas' AS STATUS,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS REGISTROS_UNICOS,
    COUNT(*) - COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS TOTAL_DUPLICATAS
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510';

-- 2. DELETAR duplicatas mantendo apenas o menor INDICE de cada grupo
-- VERSÃO OTIMIZADA: Usa NOT EXISTS em vez de NOT IN (mais rápido)
DELETE FROM RL_PROCEDIMENTO_CID pc1
WHERE pc1.DT_COMPETENCIA = '202510'
  AND EXISTS (
      -- Verifica se existe outro registro com mesmo grupo e INDICE menor
      SELECT 1
      FROM RL_PROCEDIMENTO_CID pc2
      WHERE pc2.DT_COMPETENCIA = '202510'
        AND pc2.CO_PROCEDIMENTO = pc1.CO_PROCEDIMENTO
        AND pc2.CO_CID = pc1.CO_CID
        AND pc2.DT_COMPETENCIA = pc1.DT_COMPETENCIA
        AND pc2.INDICE < pc1.INDICE
  );

-- 3. VERIFICAR após deleção
SELECT 
    'DEPOIS - Verificacao' AS STATUS,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS REGISTROS_UNICOS,
    COUNT(*) - COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS TOTAL_DUPLICATAS_RESTANTES
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510';

