-- Script para LIMPAR duplicatas em RL_PROCEDIMENTO_OCUPACAO (CBO)
-- Preserva linhas em MAIÚSCULAS (sistema antigo)
-- ATENÇÃO: Este script REMOVE dados! Execute apenas após validar!

-- 1. Verificar antes da limpeza
SELECT 
    'ANTES DA LIMPEZA' AS STATUS,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_OCUPACAO || '|' || DT_COMPETENCIA) AS REGISTROS_UNICOS,
    COUNT(*) - COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_OCUPACAO || '|' || DT_COMPETENCIA) AS TOTAL_DUPLICATAS
FROM RL_PROCEDIMENTO_OCUPACAO
WHERE DT_COMPETENCIA = '202510';

-- 2. REMOVER DUPLICATAS (preservar MAIÚSCULAS - sistema antigo)
DELETE FROM RL_PROCEDIMENTO_OCUPACAO
WHERE DT_COMPETENCIA = '202510'
  AND INDICE NOT IN (
      SELECT MIN(INDICE)
      FROM RL_PROCEDIMENTO_OCUPACAO po
      WHERE po.DT_COMPETENCIA = '202510'
        AND (
            (UPPER(TRIM(po.NO_OCUPACAO)) = TRIM(po.NO_OCUPACAO)
             AND EXISTS (
                 SELECT 1 
                 FROM RL_PROCEDIMENTO_OCUPACAO po2
                 WHERE po2.CO_PROCEDIMENTO = po.CO_PROCEDIMENTO
                   AND po2.CO_OCUPACAO = po.CO_OCUPACAO
                   AND po2.DT_COMPETENCIA = po.DT_COMPETENCIA
                   AND po2.DT_COMPETENCIA = '202510'
                   AND UPPER(TRIM(po2.NO_OCUPACAO)) = TRIM(po2.NO_OCUPACAO)
             ))
            OR
            (NOT EXISTS (
                SELECT 1 
                FROM RL_PROCEDIMENTO_OCUPACAO po3
                WHERE po3.CO_PROCEDIMENTO = po.CO_PROCEDIMENTO
                  AND po3.CO_OCUPACAO = po.CO_OCUPACAO
                  AND po3.DT_COMPETENCIA = po.DT_COMPETENCIA
                  AND po3.DT_COMPETENCIA = '202510'
                  AND UPPER(TRIM(po3.NO_OCUPACAO)) = TRIM(po3.NO_OCUPACAO)
            ))
        )
      GROUP BY po.CO_PROCEDIMENTO, po.CO_OCUPACAO, po.DT_COMPETENCIA
  );

-- 3. Verificar após limpeza
SELECT 
    'APOS LIMPEZA' AS STATUS,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_OCUPACAO || '|' || DT_COMPETENCIA) AS REGISTROS_UNICOS,
    COUNT(*) - COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_OCUPACAO || '|' || DT_COMPETENCIA) AS TOTAL_DUPLICATAS,
    SUM(CASE WHEN UPPER(TRIM(NO_OCUPACAO)) = TRIM(NO_OCUPACAO) THEN 1 ELSE 0 END) AS TOTAL_MAIUSCULAS_PRESERVADAS
FROM RL_PROCEDIMENTO_OCUPACAO
WHERE DT_COMPETENCIA = '202510';

