-- Listar todos os usos de UPPER no banco de dados
-- Verificar se há procedures, triggers, views ou outros objetos usando UPPER

-- 1. Listar todas as procedures que usam UPPER
SELECT 
    'PROCEDURE' AS TIPO_OBJETO,
    TRIM(R.RDB$PROCEDURE_NAME) AS NOME_OBJETO,
    R.RDB$PROCEDURE_SOURCE AS CODIGO_FONTE
FROM RDB$PROCEDURES R
WHERE R.RDB$PROCEDURE_SOURCE CONTAINING 'UPPER'
ORDER BY R.RDB$PROCEDURE_NAME;

-- 2. Listar todos os triggers que usam UPPER
SELECT 
    'TRIGGER' AS TIPO_OBJETO,
    TRIM(T.RDB$TRIGGER_NAME) AS NOME_OBJETO,
    T.RDB$TRIGGER_SOURCE AS CODIGO_FONTE
FROM RDB$TRIGGERS T
WHERE T.RDB$TRIGGER_SOURCE CONTAINING 'UPPER'
ORDER BY T.RDB$TRIGGER_NAME;

-- 3. Listar todas as views que usam UPPER
SELECT 
    'VIEW' AS TIPO_OBJETO,
    TRIM(R.RDB$RELATION_NAME) AS NOME_OBJETO,
    R.RDB$VIEW_SOURCE AS CODIGO_FONTE
FROM RDB$RELATIONS R
WHERE R.RDB$VIEW_SOURCE CONTAINING 'UPPER'
  AND R.RDB$SYSTEM_FLAG = 0
ORDER BY R.RDB$RELATION_NAME;

-- 4. Listar todas as constraints (check constraints podem ter UPPER)
-- Nota: RDB$CHECK_CONSTRAINTS não tem RDB$TRIGGER_SOURCE em todas as versões do Firebird
-- Vamos verificar apenas os triggers relacionados a constraints
SELECT 
    'CHECK CONSTRAINT TRIGGER' AS TIPO_OBJETO,
    TRIM(T.RDB$TRIGGER_NAME) AS NOME_OBJETO,
    TRIM(R.RDB$RELATION_NAME) AS TABELA,
    T.RDB$TRIGGER_SOURCE AS CODIGO_FONTE
FROM RDB$TRIGGERS T
INNER JOIN RDB$RELATION_CONSTRAINTS RC ON T.RDB$RELATION_NAME = RC.RDB$RELATION_NAME
INNER JOIN RDB$RELATIONS R ON RC.RDB$RELATION_NAME = R.RDB$RELATION_NAME
WHERE T.RDB$TRIGGER_SOURCE CONTAINING 'UPPER'
  AND RC.RDB$CONSTRAINT_TYPE = 'CHECK'
ORDER BY R.RDB$RELATION_NAME, T.RDB$TRIGGER_NAME;

-- 5. Verificar índices que podem usar UPPER (expressões)
-- Nota: Firebird não suporta índices funcionais diretamente, mas podemos verificar
SELECT 
    'INDEX' AS TIPO_OBJETO,
    TRIM(I.RDB$INDEX_NAME) AS NOME_OBJETO,
    TRIM(R.RDB$RELATION_NAME) AS TABELA,
    I.RDB$EXPRESSION_SOURCE AS EXPRESSAO
FROM RDB$INDICES I
INNER JOIN RDB$RELATION_CONSTRAINTS RC ON I.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
INNER JOIN RDB$RELATIONS R ON RC.RDB$RELATION_NAME = R.RDB$RELATION_NAME
WHERE I.RDB$EXPRESSION_SOURCE CONTAINING 'UPPER'
ORDER BY R.RDB$RELATION_NAME, I.RDB$INDEX_NAME;

-- 6. Resumo: Contar quantos objetos usam UPPER
SELECT 
    'PROCEDURES' AS TIPO,
    COUNT(*) AS TOTAL
FROM RDB$PROCEDURES
WHERE RDB$PROCEDURE_SOURCE CONTAINING 'UPPER'
UNION ALL
SELECT 
    'TRIGGERS' AS TIPO,
    COUNT(*) AS TOTAL
FROM RDB$TRIGGERS
WHERE RDB$TRIGGER_SOURCE CONTAINING 'UPPER'
UNION ALL
SELECT 
    'VIEWS' AS TIPO,
    COUNT(*) AS TOTAL
FROM RDB$RELATIONS
WHERE RDB$VIEW_SOURCE CONTAINING 'UPPER'
  AND RDB$SYSTEM_FLAG = 0
UNION ALL
SELECT 
    'CHECK_CONSTRAINT_TRIGGERS' AS TIPO,
    COUNT(*) AS TOTAL
FROM RDB$TRIGGERS T
INNER JOIN RDB$RELATION_CONSTRAINTS RC ON T.RDB$RELATION_NAME = RC.RDB$RELATION_NAME
WHERE T.RDB$TRIGGER_SOURCE CONTAINING 'UPPER'
  AND RC.RDB$CONSTRAINT_TYPE = 'CHECK';

