-- Script para validar se as duplicatas foram realmente removidas

-- 1. Total de registros na competência 202510
SELECT 
    'TOTAL REGISTROS' AS METRICA,
    COUNT(*) AS VALOR
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510';

-- 2. Total de grupos únicos (sem duplicatas)
SELECT 
    'REGISTROS UNICOS' AS METRICA,
    COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS VALOR
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510';

-- 3. Total de grupos com duplicatas
SELECT 
    'GRUPOS COM DUPLICATAS' AS METRICA,
    COUNT(*) AS VALOR
FROM (
    SELECT CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
    FROM RL_PROCEDIMENTO_CID
    WHERE DT_COMPETENCIA = '202510'
    GROUP BY CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
    HAVING COUNT(*) > 1
);

-- 4. Total de registros duplicados (excedentes)
SELECT 
    'REGISTROS DUPLICADOS (EXCEDENTES)' AS METRICA,
    COUNT(*) - COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS VALOR
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510';

-- 5. Exemplos de duplicatas que ainda existem (primeiras 10)
SELECT 
    'EXEMPLOS DE DUPLICATAS RESTANTES' AS INFO,
    CO_CID,
    CO_PROCEDIMENTO,
    DT_COMPETENCIA,
    COUNT(*) AS TOTAL_DUPLICATAS,
    LIST(INDICE, ', ') AS INDICES,
    LIST(SUBSTRING(NO_CID FROM 1 FOR 30), ' | ') AS NOMES
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510'
GROUP BY CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC
ROWS 10;

-- 6. Verificar se há registros em MAIÚSCULAS preservados
SELECT 
    'REGISTROS EM MAIUSCULAS' AS METRICA,
    COUNT(*) AS TOTAL
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510'
  AND UPPER(TRIM(NO_CID)) = TRIM(NO_CID)
  AND TRIM(NO_CID) <> '';

-- 7. Verificar se há registros em minúsculas/misturadas
SELECT 
    'REGISTROS EM MINUSCULAS/MISTURADAS' AS METRICA,
    COUNT(*) AS TOTAL
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510'
  AND UPPER(TRIM(NO_CID)) <> TRIM(NO_CID)
  AND TRIM(NO_CID) <> '';

