-- Verificar duplicatas em RL_PROCEDIMENTO_CID (CID10) e RL_PROCEDIMENTO_OCUPACAO (CBO)
-- Apenas visualização - não remove dados

-- ========================================
-- 1. DUPLICATAS EM RL_PROCEDIMENTO_CID (CID10)
-- ========================================

SELECT 
    'RL_PROCEDIMENTO_CID - ANTES DA LIMPEZA' AS STATUS,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS REGISTROS_UNICOS,
    COUNT(*) - COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS TOTAL_DUPLICATAS
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510';

SELECT 
    CO_CID,
    CO_PROCEDIMENTO,
    DT_COMPETENCIA,
    COUNT(*) AS TOTAL_DUPLICATAS,
    SUM(CASE WHEN UPPER(TRIM(NO_CID)) = TRIM(NO_CID) THEN 1 ELSE 0 END) AS TOTAL_MAIUSCULAS,
    SUM(CASE WHEN UPPER(TRIM(NO_CID)) <> TRIM(NO_CID) THEN 1 ELSE 0 END) AS TOTAL_MINUSCULAS_MISTURADAS
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510'
GROUP BY CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC
ROWS 20;

-- ========================================
-- 2. DUPLICATAS EM RL_PROCEDIMENTO_OCUPACAO (CBO)
-- ========================================

SELECT 
    'RL_PROCEDIMENTO_OCUPACAO - ANTES DA LIMPEZA' AS STATUS,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_OCUPACAO || '|' || DT_COMPETENCIA) AS REGISTROS_UNICOS,
    COUNT(*) - COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_OCUPACAO || '|' || DT_COMPETENCIA) AS TOTAL_DUPLICATAS
FROM RL_PROCEDIMENTO_OCUPACAO
WHERE DT_COMPETENCIA = '202510';

SELECT 
    CO_OCUPACAO,
    CO_PROCEDIMENTO,
    DT_COMPETENCIA,
    COUNT(*) AS TOTAL_DUPLICATAS,
    SUM(CASE WHEN UPPER(TRIM(NO_OCUPACAO)) = TRIM(NO_OCUPACAO) THEN 1 ELSE 0 END) AS TOTAL_MAIUSCULAS,
    SUM(CASE WHEN UPPER(TRIM(NO_OCUPACAO)) <> TRIM(NO_OCUPACAO) THEN 1 ELSE 0 END) AS TOTAL_MINUSCULAS_MISTURADAS
FROM RL_PROCEDIMENTO_OCUPACAO
WHERE DT_COMPETENCIA = '202510'
GROUP BY CO_OCUPACAO, CO_PROCEDIMENTO, DT_COMPETENCIA
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC
ROWS 20;

