-- Script: Verificar se Índices Recomendados Já Existem
-- Objetivo: Verificar antes de criar para evitar erros

-- Verificar se IDX_RL_PCID_PROC_COMP existe
SELECT 
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM RDB$INDICES 
            WHERE RDB$INDEX_NAME = 'IDX_RL_PCID_PROC_COMP'
        ) THEN 'EXISTE'
        ELSE 'NAO EXISTE'
    END AS STATUS_IDX_PROC_COMP,
    'IDX_RL_PCID_PROC_COMP' AS NOME_INDICE
FROM RDB$DATABASE;

-- Verificar se IDX_RL_PCID_CID_COMP existe
SELECT 
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM RDB$INDICES 
            WHERE RDB$INDEX_NAME = 'IDX_RL_PCID_CID_COMP'
        ) THEN 'EXISTE'
        ELSE 'NAO EXISTE'
    END AS STATUS_IDX_CID_COMP,
    'IDX_RL_PCID_CID_COMP' AS NOME_INDICE
FROM RDB$DATABASE;

-- Listar todos os índices de RL_PROCEDIMENTO_CID
SELECT 
    TRIM(I.RDB$INDEX_NAME) AS INDICE,
    TRIM(S.RDB$FIELD_NAME) AS CAMPO,
    S.RDB$FIELD_POSITION AS POSICAO
FROM RDB$INDICES I
JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME = 'RL_PROCEDIMENTO_CID'
  AND I.RDB$SYSTEM_FLAG = 0
ORDER BY I.RDB$INDEX_NAME, S.RDB$FIELD_POSITION;

