-- Verificar duplicatas em geral (todos os CIDs)

-- 1. Total de duplicatas
SELECT 
    'Total duplicatas' AS INFO,
    COUNT(*) - COUNT(DISTINCT CO_PROCEDIMENTO || '|' || CO_CID || '|' || DT_COMPETENCIA) AS TOTAL_DUPLICATAS
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510';

-- 2. Top 20 grupos com mais duplicatas
SELECT 
    FIRST 20
    CO_CID,
    CO_PROCEDIMENTO,
    COUNT(*) AS TOTAL_DUPLICATAS,
    MIN(INDICE) AS INDICE_MANTIDO,
    LIST(INDICE, ', ') AS INDICES_DUPLICATAS
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510'
GROUP BY CO_CID, CO_PROCEDIMENTO
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

