-- ============================================================================
-- Script para verificar se CBO, CID e descrições são separados por competência
-- ou se valem para todas as competências
-- ============================================================================

-- ============================================================================
-- 1. VERIFICAR ESTRUTURA DAS TABELAS PRINCIPAIS (TB_CID e TB_OCUPACAO)
-- ============================================================================

-- 1.1. Estrutura da tabela TB_CID
SELECT 
    'TB_CID' AS TABELA,
    TRIM(RF.RDB$FIELD_NAME) AS COLUNA,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    CASE WHEN RF.RDB$NULL_FLAG IS NULL THEN 'NULL' ELSE 'NOT NULL' END AS NULLABLE
FROM RDB$RELATION_FIELDS RF
INNER JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_CID'
ORDER BY RF.RDB$FIELD_POSITION;

-- 1.2. Verificar se TB_CID tem DT_COMPETENCIA
SELECT 
    'TB_CID' AS TABELA,
    CASE 
        WHEN COUNT(*) > 0 THEN 'SIM - TEM DT_COMPETENCIA (varia por competência)'
        ELSE 'NÃO - NÃO TEM DT_COMPETENCIA (vale para todas as competências)'
    END AS TEM_COMPETENCIA
FROM RDB$RELATION_FIELDS
WHERE TRIM(RDB$RELATION_NAME) = 'TB_CID'
  AND TRIM(RDB$FIELD_NAME) = 'DT_COMPETENCIA';

-- 1.3. Estrutura da tabela TB_OCUPACAO (CBO)
SELECT 
    'TB_OCUPACAO' AS TABELA,
    TRIM(RF.RDB$FIELD_NAME) AS COLUNA,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    CASE WHEN RF.RDB$NULL_FLAG IS NULL THEN 'NULL' ELSE 'NOT NULL' END AS NULLABLE
FROM RDB$RELATION_FIELDS RF
INNER JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_OCUPACAO'
ORDER BY RF.RDB$FIELD_POSITION;

-- 1.4. Verificar se TB_OCUPACAO tem DT_COMPETENCIA
SELECT 
    'TB_OCUPACAO' AS TABELA,
    CASE 
        WHEN COUNT(*) > 0 THEN 'SIM - TEM DT_COMPETENCIA (varia por competência)'
        ELSE 'NÃO - NÃO TEM DT_COMPETENCIA (vale para todas as competências)'
    END AS TEM_COMPETENCIA
FROM RDB$RELATION_FIELDS
WHERE TRIM(RDB$RELATION_NAME) = 'TB_OCUPACAO'
  AND TRIM(RDB$FIELD_NAME) = 'DT_COMPETENCIA';

-- ============================================================================
-- 2. VERIFICAR TABELAS RELACIONAIS (RL_PROCEDIMENTO_CID e RL_PROCEDIMENTO_OCUPACAO)
-- ============================================================================

-- 2.1. Estrutura da tabela RL_PROCEDIMENTO_CID
SELECT 
    'RL_PROCEDIMENTO_CID' AS TABELA,
    TRIM(RF.RDB$FIELD_NAME) AS COLUNA,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO
FROM RDB$RELATION_FIELDS RF
INNER JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) = 'RL_PROCEDIMENTO_CID'
ORDER BY RF.RDB$FIELD_POSITION;

-- 2.2. Estrutura da tabela RL_PROCEDIMENTO_OCUPACAO
SELECT 
    'RL_PROCEDIMENTO_OCUPACAO' AS TABELA,
    TRIM(RF.RDB$FIELD_NAME) AS COLUNA,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO
FROM RDB$RELATION_FIELDS RF
INNER JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) = 'RL_PROCEDIMENTO_OCUPACAO'
ORDER BY RF.RDB$FIELD_POSITION;

-- ============================================================================
-- 3. VERIFICAR DADOS: QUANTIDADE DE REGISTROS E COMPETÊNCIAS
-- ============================================================================

-- 3.1. Total de registros em TB_CID
SELECT 
    'TB_CID' AS TABELA,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_CID) AS TOTAL_CIDS_UNICOS
FROM TB_CID;

-- 3.2. Verificar se há CIDs duplicados em TB_CID (se tiver DT_COMPETENCIA)
SELECT 
    'TB_CID - CIDs Duplicados' AS VERIFICACAO,
    CO_CID,
    COUNT(*) AS TOTAL_OCORRENCIAS
FROM TB_CID
GROUP BY CO_CID
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- 3.3. Total de registros em TB_OCUPACAO
SELECT 
    'TB_OCUPACAO' AS TABELA,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_OCUPACAO) AS TOTAL_CBOS_UNICOS
FROM TB_OCUPACAO;

-- 3.4. Verificar se há CBOs duplicados em TB_OCUPACAO (se tiver DT_COMPETENCIA)
SELECT 
    'TB_OCUPACAO - CBOs Duplicados' AS VERIFICACAO,
    CO_OCUPACAO,
    COUNT(*) AS TOTAL_OCORRENCIAS
FROM TB_OCUPACAO
GROUP BY CO_OCUPACAO
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- 3.5. Competências em RL_PROCEDIMENTO_CID
SELECT 
    'RL_PROCEDIMENTO_CID' AS TABELA,
    COUNT(DISTINCT DT_COMPETENCIA) AS TOTAL_COMPETENCIAS,
    MIN(DT_COMPETENCIA) AS PRIMEIRA_COMPETENCIA,
    MAX(DT_COMPETENCIA) AS ULTIMA_COMPETENCIA,
    COUNT(*) AS TOTAL_RELACIONAMENTOS
FROM RL_PROCEDIMENTO_CID;

-- 3.6. Competências em RL_PROCEDIMENTO_OCUPACAO
SELECT 
    'RL_PROCEDIMENTO_OCUPACAO' AS TABELA,
    COUNT(DISTINCT DT_COMPETENCIA) AS TOTAL_COMPETENCIAS,
    MIN(DT_COMPETENCIA) AS PRIMEIRA_COMPETENCIA,
    MAX(DT_COMPETENCIA) AS ULTIMA_COMPETENCIA,
    COUNT(*) AS TOTAL_RELACIONAMENTOS
FROM RL_PROCEDIMENTO_OCUPACAO;

-- ============================================================================
-- 4. VERIFICAR DESCRIÇÕES: SE VARIAM POR COMPETÊNCIA
-- ============================================================================

-- 4.1. Verificar se descrições de CID variam por competência
-- (comparar NO_CID em TB_CID vs NO_CID em RL_PROCEDIMENTO_CID)
SELECT 
    'Verificação: Descrições CID' AS VERIFICACAO,
    c.CO_CID,
    c.NO_CID AS DESCRICAO_TB_CID,
    COUNT(DISTINCT rl.NO_CID) AS TOTAL_DESCRICOES_DIFERENTES_RL,
    COUNT(DISTINCT rl.DT_COMPETENCIA) AS TOTAL_COMPETENCIAS_DIFERENTES
FROM TB_CID c
LEFT JOIN RL_PROCEDIMENTO_CID rl ON c.CO_CID = rl.CO_CID
GROUP BY c.CO_CID, c.NO_CID
HAVING COUNT(DISTINCT rl.NO_CID) > 1
ORDER BY COUNT(DISTINCT rl.NO_CID) DESC
ROWS 20;

-- 4.2. Verificar se descrições de CBO variam por competência
-- (comparar NO_OCUPACAO em TB_OCUPACAO vs NO_OCUPACAO em RL_PROCEDIMENTO_OCUPACAO)
SELECT 
    'Verificação: Descrições CBO' AS VERIFICACAO,
    o.CO_OCUPACAO,
    o.NO_OCUPACAO AS DESCRICAO_TB_OCUPACAO,
    COUNT(DISTINCT rl.NO_OCUPACAO) AS TOTAL_DESCRICOES_DIFERENTES_RL,
    COUNT(DISTINCT rl.DT_COMPETENCIA) AS TOTAL_COMPETENCIAS_DIFERENTES
FROM TB_OCUPACAO o
LEFT JOIN RL_PROCEDIMENTO_OCUPACAO rl ON o.CO_OCUPACAO = rl.CO_OCUPACAO
GROUP BY o.CO_OCUPACAO, o.NO_OCUPACAO
HAVING COUNT(DISTINCT rl.NO_OCUPACAO) > 1
ORDER BY COUNT(DISTINCT rl.NO_OCUPACAO) DESC
ROWS 20;

-- 4.3. Exemplo: Verificar um CID específico em diferentes competências
SELECT 
    'Exemplo: CID A000 em diferentes competências' AS VERIFICACAO,
    rl.DT_COMPETENCIA,
    c.NO_CID AS DESCRICAO_TB_CID,
    rl.NO_CID AS DESCRICAO_RL_PROCEDIMENTO_CID,
    CASE 
        WHEN TRIM(c.NO_CID) = TRIM(rl.NO_CID) THEN 'IGUAL'
        ELSE 'DIFERENTE'
    END AS COMPARACAO
FROM RL_PROCEDIMENTO_CID rl
INNER JOIN TB_CID c ON rl.CO_CID = c.CO_CID
WHERE rl.CO_CID = 'A000'
  AND rl.DT_COMPETENCIA IN (
      SELECT DISTINCT DT_COMPETENCIA 
      FROM RL_PROCEDIMENTO_CID 
      WHERE CO_CID = 'A000' 
      ORDER BY DT_COMPETENCIA DESC 
      ROWS 5
  )
ORDER BY rl.DT_COMPETENCIA DESC;

-- 4.4. Exemplo: Verificar um CBO específico em diferentes competências
SELECT 
    'Exemplo: CBO 010105 em diferentes competências' AS VERIFICACAO,
    rl.DT_COMPETENCIA,
    o.NO_OCUPACAO AS DESCRICAO_TB_OCUPACAO,
    rl.NO_OCUPACAO AS DESCRICAO_RL_PROCEDIMENTO_OCUPACAO,
    CASE 
        WHEN TRIM(o.NO_OCUPACAO) = TRIM(rl.NO_OCUPACAO) THEN 'IGUAL'
        ELSE 'DIFERENTE'
    END AS COMPARACAO
FROM RL_PROCEDIMENTO_OCUPACAO rl
INNER JOIN TB_OCUPACAO o ON rl.CO_OCUPACAO = o.CO_OCUPACAO
WHERE rl.CO_OCUPACAO = '010105'
  AND rl.DT_COMPETENCIA IN (
      SELECT DISTINCT DT_COMPETENCIA 
      FROM RL_PROCEDIMENTO_OCUPACAO 
      WHERE CO_OCUPACAO = '010105' 
      ORDER BY DT_COMPETENCIA DESC 
      ROWS 5
  )
ORDER BY rl.DT_COMPETENCIA DESC;

-- ============================================================================
-- 5. RESUMO FINAL
-- ============================================================================

SELECT 
    '=== RESUMO FINAL ===' AS RESUMO,
    '' AS DETALHES;

SELECT 
    'TB_CID' AS TABELA,
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM RDB$RELATION_FIELDS 
            WHERE TRIM(RDB$RELATION_NAME) = 'TB_CID' 
            AND TRIM(RDB$FIELD_NAME) = 'DT_COMPETENCIA'
        ) THEN 'SEPARADO POR COMPETÊNCIA'
        ELSE 'VALE PARA TODAS AS COMPETÊNCIAS'
    END AS STATUS_COMPETENCIA,
    (SELECT COUNT(*) FROM TB_CID) AS TOTAL_REGISTROS;

SELECT 
    'TB_OCUPACAO (CBO)' AS TABELA,
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM RDB$RELATION_FIELDS 
            WHERE TRIM(RDB$RELATION_NAME) = 'TB_OCUPACAO' 
            AND TRIM(RDB$FIELD_NAME) = 'DT_COMPETENCIA'
        ) THEN 'SEPARADO POR COMPETÊNCIA'
        ELSE 'VALE PARA TODAS AS COMPETÊNCIAS'
    END AS STATUS_COMPETENCIA,
    (SELECT COUNT(*) FROM TB_OCUPACAO) AS TOTAL_REGISTROS;

SELECT 
    'RL_PROCEDIMENTO_CID' AS TABELA,
    'SEPARADO POR COMPETÊNCIA' AS STATUS_COMPETENCIA,
    COUNT(DISTINCT DT_COMPETENCIA) AS TOTAL_COMPETENCIAS,
    COUNT(*) AS TOTAL_RELACIONAMENTOS
FROM RL_PROCEDIMENTO_CID;

SELECT 
    'RL_PROCEDIMENTO_OCUPACAO' AS TABELA,
    'SEPARADO POR COMPETÊNCIA' AS STATUS_COMPETENCIA,
    COUNT(DISTINCT DT_COMPETENCIA) AS TOTAL_COMPETENCIAS,
    COUNT(*) AS TOTAL_RELACIONAMENTOS
FROM RL_PROCEDIMENTO_OCUPACAO;

