-- Verificar estrutura da tabela TB_CID
-- Verificar se tem DT_COMPETENCIA e como está relacionada com competências

-- 1. Estrutura da tabela TB_CID
SELECT 
    RF.RDB$FIELD_NAME AS COLUNA,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    RF.RDB$NULL_FLAG AS NOT_NULL
FROM RDB$RELATION_FIELDS RF
INNER JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_CID'
ORDER BY RF.RDB$FIELD_POSITION;

-- 2. Verificar se TB_CID tem DT_COMPETENCIA
SELECT 
    COUNT(*) AS TEM_DT_COMPETENCIA
FROM RDB$RELATION_FIELDS
WHERE TRIM(RDB$RELATION_NAME) = 'TB_CID'
  AND TRIM(RDB$FIELD_NAME) = 'DT_COMPETENCIA';

-- 3. Verificar relacionamento RL_PROCEDIMENTO_CID (tem DT_COMPETENCIA)
SELECT 
    RF.RDB$FIELD_NAME AS COLUNA,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO
FROM RDB$RELATION_FIELDS RF
INNER JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) = 'RL_PROCEDIMENTO_CID'
ORDER BY RF.RDB$FIELD_POSITION;

-- 4. Verificar quantas competências diferentes existem em RL_PROCEDIMENTO_CID
SELECT 
    COUNT(DISTINCT DT_COMPETENCIA) AS TOTAL_COMPETENCIAS,
    MIN(DT_COMPETENCIA) AS PRIMEIRA_COMPETENCIA,
    MAX(DT_COMPETENCIA) AS ULTIMA_COMPETENCIA
FROM RL_PROCEDIMENTO_CID;

-- 5. Listar competências únicas em RL_PROCEDIMENTO_CID
SELECT DISTINCT 
    DT_COMPETENCIA,
    COUNT(*) AS TOTAL_RELACIONAMENTOS
FROM RL_PROCEDIMENTO_CID
GROUP BY DT_COMPETENCIA
ORDER BY DT_COMPETENCIA DESC;

-- 6. Verificar se TB_CID tem registros duplicados por competência (se tiver DT_COMPETENCIA)
-- Se não tiver DT_COMPETENCIA, significa que CID é único e não varia por competência
SELECT 
    CO_CID,
    COUNT(*) AS TOTAL_OCORRENCIAS
FROM TB_CID
GROUP BY CO_CID
HAVING COUNT(*) > 1;

