-- Verificar duplicatas em RL_PROCEDIMENTO_CID
-- Verificar se há registros duplicados (mesmo CO_CID + CO_PROCEDIMENTO + DT_COMPETENCIA)

-- 1. Verificar constraints de unicidade em RL_PROCEDIMENTO_CID
SELECT 
    RC.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME,
    RC.RDB$CONSTRAINT_TYPE AS CONSTRAINT_TYPE,
    TRIM(RC.RDB$RELATION_NAME) AS TABELA,
    LIST(TRIM(ISG.RDB$FIELD_NAME), ', ') AS CAMPOS
FROM RDB$RELATION_CONSTRAINTS RC
LEFT JOIN RDB$INDEX_SEGMENTS ISG ON RC.RDB$INDEX_NAME = ISG.RDB$INDEX_NAME
WHERE TRIM(RC.RDB$RELATION_NAME) = 'RL_PROCEDIMENTO_CID'
GROUP BY RC.RDB$CONSTRAINT_NAME, RC.RDB$CONSTRAINT_TYPE, RC.RDB$RELATION_NAME
ORDER BY RC.RDB$CONSTRAINT_TYPE;

-- 2. Verificar duplicatas exatas (mesmo CO_CID + CO_PROCEDIMENTO + DT_COMPETENCIA)
SELECT 
    CO_CID,
    CO_PROCEDIMENTO,
    DT_COMPETENCIA,
    COUNT(*) AS TOTAL_DUPLICATAS
FROM RL_PROCEDIMENTO_CID
GROUP BY CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- 3. Verificar duplicatas por competência 202510 (10/2025)
SELECT 
    CO_CID,
    CO_PROCEDIMENTO,
    COUNT(*) AS TOTAL_DUPLICATAS,
    LIST(DISTINCT ST_PRINCIPAL, ', ') AS STATUS_PRINCIPAL
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510'
GROUP BY CO_CID, CO_PROCEDIMENTO
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- 4. Verificar se há diferenças de encoding (UPPER vs não-UPPER) causando duplicatas
-- Comparar NO_CID com diferentes encodings
SELECT 
    pc1.CO_CID,
    pc1.CO_PROCEDIMENTO,
    pc1.DT_COMPETENCIA,
    pc1.NO_CID AS NO_CID_1,
    pc2.NO_CID AS NO_CID_2,
    CASE 
        WHEN UPPER(TRIM(pc1.NO_CID)) = UPPER(TRIM(pc2.NO_CID)) THEN 'MESMO (UPPER)'
        ELSE 'DIFERENTE'
    END AS COMPARACAO
FROM RL_PROCEDIMENTO_CID pc1
INNER JOIN RL_PROCEDIMENTO_CID pc2 
    ON pc1.CO_CID = pc2.CO_CID 
    AND pc1.CO_PROCEDIMENTO = pc2.CO_PROCEDIMENTO
    AND pc1.DT_COMPETENCIA = pc2.DT_COMPETENCIA
    AND pc1.INDICE < pc2.INDICE
WHERE pc1.DT_COMPETENCIA = '202510'
ORDER BY pc1.CO_CID, pc1.CO_PROCEDIMENTO;

-- 5. Verificar se há CIDs da competência 202006 (06/2020) aparecendo em 202510
SELECT 
    pc.CO_CID,
    pc.CO_PROCEDIMENTO,
    pc.DT_COMPETENCIA,
    pc.NO_CID,
    c.NO_CID AS NO_CID_TB_CID
FROM RL_PROCEDIMENTO_CID pc
INNER JOIN TB_CID c ON pc.CO_CID = c.CO_CID
WHERE pc.DT_COMPETENCIA = '202510'
  AND EXISTS (
      SELECT 1 
      FROM RL_PROCEDIMENTO_CID pc2 
      WHERE pc2.CO_CID = pc.CO_CID 
        AND pc2.CO_PROCEDIMENTO = pc.CO_PROCEDIMENTO
        AND pc2.DT_COMPETENCIA = '202006'
  )
ORDER BY pc.CO_CID, pc.CO_PROCEDIMENTO;

-- 6. Contar total de registros por competência
SELECT 
    DT_COMPETENCIA,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CO_CID) AS TOTAL_CIDS_UNICOS,
    COUNT(DISTINCT CO_PROCEDIMENTO) AS TOTAL_PROCEDIMENTOS_UNICOS
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA IN ('202006', '202510')
GROUP BY DT_COMPETENCIA
ORDER BY DT_COMPETENCIA;

-- 7. Verificar registros com encoding corrompido (contém caracteres estranhos)
SELECT 
    CO_CID,
    CO_PROCEDIMENTO,
    DT_COMPETENCIA,
    NO_CID,
    CASE 
        WHEN NO_CID CONTAINING 'Ã' THEN 'ENCODING_CORROMPIDO'
        WHEN NO_CID CONTAINING '?' THEN 'CARACTERE_INVALIDO'
        ELSE 'OK'
    END AS STATUS_ENCODING
FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510'
  AND (NO_CID CONTAINING 'Ã' OR NO_CID CONTAINING '?')
ORDER BY CO_CID, CO_PROCEDIMENTO;

