-- ============================================================================
-- Verificação Rápida: CBO, CID e Descrições por Competência
-- Consultas pequenas e focadas
-- ============================================================================

-- 1. TB_CID tem DT_COMPETENCIA?
SELECT 
    'TB_CID tem DT_COMPETENCIA?' AS PERGUNTA,
    CASE 
        WHEN COUNT(*) > 0 THEN 'SIM'
        ELSE 'NÃO'
    END AS RESPOSTA
FROM RDB$RELATION_FIELDS
WHERE TRIM(RDB$RELATION_NAME) = 'TB_CID'
  AND TRIM(RDB$FIELD_NAME) = 'DT_COMPETENCIA';

-- 2. TB_OCUPACAO tem DT_COMPETENCIA?
SELECT 
    'TB_OCUPACAO tem DT_COMPETENCIA?' AS PERGUNTA,
    CASE 
        WHEN COUNT(*) > 0 THEN 'SIM'
        ELSE 'NÃO'
    END AS RESPOSTA
FROM RDB$RELATION_FIELDS
WHERE TRIM(RDB$RELATION_NAME) = 'TB_OCUPACAO'
  AND TRIM(RDB$FIELD_NAME) = 'DT_COMPETENCIA';

-- 3. Total de registros TB_CID
SELECT 
    'Total TB_CID' AS INFO,
    COUNT(*) AS TOTAL
FROM TB_CID;

-- 4. Total de registros TB_OCUPACAO
SELECT 
    'Total TB_OCUPACAO' AS INFO,
    COUNT(*) AS TOTAL
FROM TB_OCUPACAO;

-- 5. Competências em RL_PROCEDIMENTO_CID
SELECT 
    'RL_PROCEDIMENTO_CID' AS TABELA,
    COUNT(DISTINCT DT_COMPETENCIA) AS TOTAL_COMPETENCIAS,
    MIN(DT_COMPETENCIA) AS PRIMEIRA,
    MAX(DT_COMPETENCIA) AS ULTIMA
FROM RL_PROCEDIMENTO_CID;

-- 6. Competências em RL_PROCEDIMENTO_OCUPACAO
SELECT 
    'RL_PROCEDIMENTO_OCUPACAO' AS TABELA,
    COUNT(DISTINCT DT_COMPETENCIA) AS TOTAL_COMPETENCIAS,
    MIN(DT_COMPETENCIA) AS PRIMEIRA,
    MAX(DT_COMPETENCIA) AS ULTIMA
FROM RL_PROCEDIMENTO_OCUPACAO;

