-- Script para verificar estrutura das tabelas de Serviço e Classificação
-- Objetivo: Entender como cadastrar Serviço/Classificação

-- 1. Verificar estrutura da tabela TB_SERVICO
SELECT 
    RF.RDB$FIELD_NAME AS COLUMN_NAME,
    RF.RDB$FIELD_SOURCE AS FIELD_SOURCE,
    CASE F.RDB$FIELD_TYPE
        WHEN 7 THEN 'SMALLINT'
        WHEN 8 THEN 'INTEGER'
        WHEN 9 THEN 'QUAD'
        WHEN 10 THEN 'FLOAT'
        WHEN 11 THEN 'DOUBLE PRECISION'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 14 THEN 'CHAR'
        WHEN 16 THEN 'BIGINT'
        WHEN 27 THEN 'DOUBLE PRECISION'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        WHEN 40 THEN 'CSTRING'
        WHEN 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS FIELD_TYPE,
    F.RDB$FIELD_LENGTH AS FIELD_LENGTH,
    RF.RDB$NULL_FLAG AS NULL_FLAG
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_SERVICO'
ORDER BY RF.RDB$FIELD_POSITION;

-- 2. Verificar estrutura da tabela TB_SERVICO_CLASSIFICACAO
SELECT 
    RF.RDB$FIELD_NAME AS COLUMN_NAME,
    RF.RDB$FIELD_SOURCE AS FIELD_SOURCE,
    CASE F.RDB$FIELD_TYPE
        WHEN 7 THEN 'SMALLINT'
        WHEN 8 THEN 'INTEGER'
        WHEN 9 THEN 'QUAD'
        WHEN 10 THEN 'FLOAT'
        WHEN 11 THEN 'DOUBLE PRECISION'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 14 THEN 'CHAR'
        WHEN 16 THEN 'BIGINT'
        WHEN 27 THEN 'DOUBLE PRECISION'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        WHEN 40 THEN 'CSTRING'
        WHEN 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS FIELD_TYPE,
    F.RDB$FIELD_LENGTH AS FIELD_LENGTH,
    RF.RDB$NULL_FLAG AS NULL_FLAG
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_SERVICO_CLASSIFICACAO'
ORDER BY RF.RDB$FIELD_POSITION;

-- 3. Verificar índices e chaves primárias
SELECT 
    I.RDB$INDEX_NAME,
    I.RDB$RELATION_NAME,
    I.RDB$UNIQUE_FLAG,
    S.RDB$FIELD_NAME,
    S.RDB$FIELD_POSITION
FROM RDB$INDICES I
LEFT JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME IN ('TB_SERVICO', 'TB_SERVICO_CLASSIFICACAO')
ORDER BY I.RDB$RELATION_NAME, I.RDB$INDEX_NAME, S.RDB$FIELD_POSITION;

-- 4. Consultar alguns registros de exemplo da TB_SERVICO
SELECT 
    CO_SERVICO,
    NO_SERVICO,
    DT_COMPETENCIA
FROM TB_SERVICO
ORDER BY CO_SERVICO
ROWS 10;

-- 5. Consultar alguns registros de exemplo da TB_SERVICO_CLASSIFICACAO
SELECT 
    CO_SERVICO,
    CO_CLASSIFICACAO,
    NO_CLASSIFICACAO,
    DT_COMPETENCIA
FROM TB_SERVICO_CLASSIFICACAO
ORDER BY CO_SERVICO, CO_CLASSIFICACAO
ROWS 10;

-- 6. Consultar view completa com JOIN (como aparece na imagem)
SELECT 
    ROW_NUMBER() OVER (ORDER BY sc.CO_SERVICO, sc.CO_CLASSIFICACAO) AS ID,
    sc.CO_SERVICO AS SERV,
    CAST(s.NO_SERVICO AS VARCHAR(120)) AS DESCRICAO_SERVICO,
    sc.CO_CLASSIFICACAO AS CLASS,
    CAST(sc.NO_CLASSIFICACAO AS VARCHAR(150)) AS DESCRICAO_CLASSIFICACAO,
    sc.DT_COMPETENCIA
FROM TB_SERVICO_CLASSIFICACAO sc
INNER JOIN TB_SERVICO s ON sc.CO_SERVICO = s.CO_SERVICO 
    AND sc.DT_COMPETENCIA = s.DT_COMPETENCIA
ORDER BY sc.CO_SERVICO, sc.CO_CLASSIFICACAO
ROWS 20;

