-- Script: Verificar Índices Existentes nas Tabelas Críticas
-- Objetivo: Analisar índices existentes para otimização de queries

-- ============================================
-- 1. Verificar índices em RL_PROCEDIMENTO_CID
-- ============================================
SELECT 
    TRIM(I.RDB$INDEX_NAME) AS INDICE,
    TRIM(I.RDB$RELATION_NAME) AS TABELA,
    TRIM(S.RDB$FIELD_NAME) AS CAMPO,
    S.RDB$FIELD_POSITION AS POSICAO,
    CASE WHEN I.RDB$UNIQUE_FLAG = 1 THEN 'SIM' ELSE 'NÃO' END AS UNICO,
    CASE WHEN I.RDB$INDEX_TYPE = 1 THEN 'DESCENDENTE' ELSE 'ASCENDENTE' END AS TIPO
FROM RDB$INDICES I
JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME = 'RL_PROCEDIMENTO_CID'
  AND I.RDB$SYSTEM_FLAG = 0
ORDER BY I.RDB$INDEX_NAME, S.RDB$FIELD_POSITION;

-- ============================================
-- 2. Verificar índices em TB_CID
-- ============================================
SELECT 
    TRIM(I.RDB$INDEX_NAME) AS INDICE,
    TRIM(I.RDB$RELATION_NAME) AS TABELA,
    TRIM(S.RDB$FIELD_NAME) AS CAMPO,
    S.RDB$FIELD_POSITION AS POSICAO,
    CASE WHEN I.RDB$UNIQUE_FLAG = 1 THEN 'SIM' ELSE 'NÃO' END AS UNICO,
    CASE WHEN I.RDB$INDEX_TYPE = 1 THEN 'DESCENDENTE' ELSE 'ASCENDENTE' END AS TIPO
FROM RDB$INDICES I
JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME = 'TB_CID'
  AND I.RDB$SYSTEM_FLAG = 0
ORDER BY I.RDB$INDEX_NAME, S.RDB$FIELD_POSITION;

-- ============================================
-- 3. Verificar índices em TB_PROCEDIMENTO
-- ============================================
SELECT 
    TRIM(I.RDB$INDEX_NAME) AS INDICE,
    TRIM(I.RDB$RELATION_NAME) AS TABELA,
    TRIM(S.RDB$FIELD_NAME) AS CAMPO,
    S.RDB$FIELD_POSITION AS POSICAO,
    CASE WHEN I.RDB$UNIQUE_FLAG = 1 THEN 'SIM' ELSE 'NÃO' END AS UNICO,
    CASE WHEN I.RDB$INDEX_TYPE = 1 THEN 'DESCENDENTE' ELSE 'ASCENDENTE' END AS TIPO
FROM RDB$INDICES I
JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
  AND I.RDB$SYSTEM_FLAG = 0
ORDER BY I.RDB$INDEX_NAME, S.RDB$FIELD_POSITION;

-- ============================================
-- 4. Verificar chaves primárias (PKs)
-- ============================================
SELECT 
    TRIM(RC.RDB$CONSTRAINT_NAME) AS CONSTRAINT_NAME,
    TRIM(RC.RDB$RELATION_NAME) AS TABELA,
    TRIM(S.RDB$FIELD_NAME) AS CAMPO_PK,
    S.RDB$FIELD_POSITION AS POSICAO
FROM RDB$RELATION_CONSTRAINTS RC
JOIN RDB$INDEX_SEGMENTS S ON RC.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE RC.RDB$CONSTRAINT_TYPE = 'PRIMARY KEY'
  AND RC.RDB$RELATION_NAME IN ('RL_PROCEDIMENTO_CID', 'TB_CID', 'TB_PROCEDIMENTO')
ORDER BY RC.RDB$RELATION_NAME, S.RDB$FIELD_POSITION;

-- ============================================
-- 5. Verificar estatísticas de tabelas (se disponível)
-- ============================================
-- Nota: RDB$STATISTICS pode não estar disponível em todas as versões do Firebird
SELECT 
    TRIM(R.RDB$RELATION_NAME) AS TABELA,
    R.RDB$RELATION_TYPE AS TIPO_RELACAO
FROM RDB$RELATIONS R
WHERE R.RDB$RELATION_NAME IN ('RL_PROCEDIMENTO_CID', 'TB_CID', 'TB_PROCEDIMENTO')
  AND R.RDB$SYSTEM_FLAG = 0
ORDER BY R.RDB$RELATION_NAME;

