-- Verifica tamanhos das colunas no banco e compara com o layout esperado

-- TB_RUBRICA
SELECT 
    'TB_RUBRICA' AS TABELA,
    TRIM(RF.RDB$FIELD_NAME) AS COLUNA,
    F.RDB$FIELD_LENGTH AS TAMANHO_BANCO,
    CASE TRIM(RF.RDB$FIELD_NAME)
        WHEN 'CO_RUBRICA' THEN 6
        WHEN 'NO_RUBRICA' THEN 100
        WHEN 'DT_COMPETENCIA' THEN 6
        ELSE 0
    END AS TAMANHO_ESPERADO,
    CASE 
        WHEN F.RDB$FIELD_LENGTH < CASE TRIM(RF.RDB$FIELD_NAME)
            WHEN 'CO_RUBRICA' THEN 6
            WHEN 'NO_RUBRICA' THEN 100
            WHEN 'DT_COMPETENCIA' THEN 6
            ELSE 0
        END THEN 'PRECISA AJUSTAR'
        ELSE 'OK'
    END AS STATUS
FROM RDB$RELATION_FIELDS RF
JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_RUBRICA'
  AND TRIM(RF.RDB$FIELD_NAME) IN ('CO_RUBRICA', 'NO_RUBRICA', 'DT_COMPETENCIA')
ORDER BY RF.RDB$FIELD_POSITION;

-- TB_CID
SELECT 
    'TB_CID' AS TABELA,
    TRIM(RF.RDB$FIELD_NAME) AS COLUNA,
    F.RDB$FIELD_LENGTH AS TAMANHO_BANCO,
    CASE TRIM(RF.RDB$FIELD_NAME)
        WHEN 'CO_CID' THEN 4
        WHEN 'NO_CID' THEN 100
        WHEN 'TP_AGRAVO' THEN 1
        WHEN 'TP_SEXO' THEN 1
        WHEN 'TP_ESTADIO' THEN 1
        ELSE 0
    END AS TAMANHO_ESPERADO,
    CASE 
        WHEN F.RDB$FIELD_LENGTH < CASE TRIM(RF.RDB$FIELD_NAME)
            WHEN 'CO_CID' THEN 4
            WHEN 'NO_CID' THEN 100
            WHEN 'TP_AGRAVO' THEN 1
            WHEN 'TP_SEXO' THEN 1
            WHEN 'TP_ESTADIO' THEN 1
            ELSE 0
        END THEN 'PRECISA AJUSTAR'
        ELSE 'OK'
    END AS STATUS
FROM RDB$RELATION_FIELDS RF
JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) = 'TB_CID'
  AND TRIM(RF.RDB$FIELD_NAME) IN ('CO_CID', 'NO_CID', 'TP_AGRAVO', 'TP_SEXO', 'TP_ESTADIO')
ORDER BY RF.RDB$FIELD_POSITION;

