-- Verifica os tamanhos atuais das colunas após o aumento

SELECT 
    TRIM(RF.RDB$RELATION_NAME) AS TABELA,
    TRIM(RF.RDB$FIELD_NAME) AS COLUNA,
    F.RDB$FIELD_LENGTH AS TAMANHO_BYTES,
    CASE 
        WHEN F.RDB$FIELD_LENGTH >= 200 THEN 'OK - 200+ bytes'
        WHEN F.RDB$FIELD_LENGTH >= 100 THEN 'OK - 100+ bytes'
        ELSE 'ATENÇÃO - Menor que 100 bytes'
    END AS STATUS
FROM RDB$RELATION_FIELDS RF
JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE TRIM(RF.RDB$RELATION_NAME) IN ('TB_RUBRICA', 'TB_CID')
  AND TRIM(RF.RDB$FIELD_NAME) IN ('NO_RUBRICA', 'NO_CID', 'CO_RUBRICA', 'DT_COMPETENCIA', 'CO_CID')
ORDER BY TABELA, COLUNA;

