-- Verificar tipo do campo DS_PROCEDIMENTO
SELECT 
    f.RDB$FIELD_NAME,
    t.RDB$TYPE_NAME,
    f.RDB$FIELD_LENGTH
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f ON rf.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
JOIN RDB$TYPES t ON f.RDB$FIELD_TYPE = t.RDB$TYPE
WHERE rf.RDB$RELATION_NAME = 'TB_DESCRICAO'
  AND rf.RDB$FIELD_NAME = 'DS_PROCEDIMENTO'
  AND t.RDB$FIELD_NAME = 'RDB$FIELD_TYPE';
