-- Script para verificar a estrutura completa da tabela TB_PROCOMUNS
-- Esta tabela parece ser onde os procedimentos comuns são armazenados

-- 1. Verificar estrutura completa da tabela TB_PROCOMUNS
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 27 THEN 'DOUBLE PRECISION'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    RF.RDB$NULL_FLAG AS NOT_NULL
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_PROCOMUNS'
ORDER BY RF.RDB$FIELD_POSITION;

-- 2. Verificar índices da tabela TB_PROCOMUNS
SELECT 
    I.RDB$INDEX_NAME AS INDICE,
    I.RDB$UNIQUE_FLAG AS UNICO,
    I.RDB$INDEX_TYPE AS TIPO
FROM RDB$INDICES I
WHERE I.RDB$RELATION_NAME = 'TB_PROCOMUNS'
  AND I.RDB$SYSTEM_FLAG = 0;

-- 3. Verificar chaves primárias e estrangeiras
SELECT 
    RC.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME,
    RC.RDB$CONSTRAINT_TYPE AS TIPO,
    S.RDB$FIELD_NAME AS CAMPO
FROM RDB$RELATION_CONSTRAINTS RC
LEFT JOIN RDB$INDEX_SEGMENTS S ON RC.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE RC.RDB$RELATION_NAME = 'TB_PROCOMUNS'
ORDER BY RC.RDB$CONSTRAINT_TYPE, S.RDB$FIELD_POSITION;

-- 4. Ver alguns registros de exemplo (primeiros 10)
SELECT FIRST 10 *
FROM TB_PROCOMUNS
ORDER BY CO_PROCEDIMENTO;

-- 5. Contar total de registros
SELECT COUNT(*) AS TOTAL_REGISTROS
FROM TB_PROCOMUNS;

