-- Verificar campos de RL_PROCEDIMENTO_INCREMENTO
SELECT 
    rf.RDB$FIELD_NAME as CAMPO
FROM RDB$RELATION_FIELDS rf
WHERE rf.RDB$RELATION_NAME = 'RL_PROCEDIMENTO_INCREMENTO'
ORDER BY rf.RDB$FIELD_POSITION;
