-- Verificar estrutura e dados da tabela TB_DETALHE e RL_PROCEDIMENTO_DETALHE

-- 1. Ver estrutura de TB_DETALHE
SELECT FIRST 5 * FROM TB_DETALHE WHERE DT_COMPETENCIA = '201108';

-- 2. Ver estrutura de RL_PROCEDIMENTO_DETALHE
SELECT FIRST 5 * FROM RL_PROCEDIMENTO_DETALHE WHERE DT_COMPETENCIA = '201108';

-- 3. Ver exemplo completo com JOIN
SELECT 
    pr.CO_PROCEDIMENTO,
    pr.NO_PROCEDIMENTO,
    det.CO_DETALHE,
    det.NO_DETALHE,
    det.DT_COMPETENCIA as COMPETENCIA_DETALHE,
    prdet.DT_COMPETENCIA as COMPETENCIA_REL,
    prdet.CO_PROCEDIMENTO,
    prdet.CO_DETALHE
FROM TB_PROCEDIMENTO pr
INNER JOIN RL_PROCEDIMENTO_DETALHE prdet ON pr.CO_PROCEDIMENTO = prdet.CO_PROCEDIMENTO
INNER JOIN TB_DETALHE det ON prdet.CO_DETALHE = det.CO_DETALHE
WHERE pr.CO_PROCEDIMENTO = '0101020074'
  AND pr.DT_COMPETENCIA = '201108'
  AND prdet.DT_COMPETENCIA = '201108'
ORDER BY det.CO_DETALHE;
