-- Verificar tabela TB_DESCRICAO_DETALHE para descrição longa

-- 1. Ver estrutura de TB_DESCRICAO_DETALHE
SELECT FIRST 5 * FROM TB_DESCRICAO_DETALHE WHERE DT_COMPETENCIA = '201108';

-- 2. Buscar descrição do detalhe "020" (MONITORAMENTO DO CEO)
SELECT 
    dd.CO_DETALHE,
    dd.DE_DETALHE,
    dd.DT_COMPETENCIA
FROM TB_DESCRICAO_DETALHE dd
WHERE dd.CO_DETALHE = '020'
  AND dd.DT_COMPETENCIA = '201108';

-- 3. Ver relacionamento completo
SELECT 
    d.CO_DETALHE,
    d.NO_DETALHE,
    dd.DE_DETALHE,
    pd.DT_COMPETENCIA
FROM RL_PROCEDIMENTO_DETALHE pd
INNER JOIN TB_DETALHE d ON pd.CO_DETALHE = d.CO_DETALHE
LEFT JOIN TB_DESCRICAO_DETALHE dd ON d.CO_DETALHE = dd.CO_DETALHE AND d.DT_COMPETENCIA = dd.DT_COMPETENCIA
WHERE pd.CO_PROCEDIMENTO = '0101020074'
  AND pd.DT_COMPETENCIA = '201108'
ORDER BY d.CO_DETALHE;
