-- Script para verificar a competência ativa
SELECT 
    DT_COMPETENCIA AS COMPETENCIA_ATIVA,
    ST_ATIVA AS STATUS,
    DT_ATIVACAO AS DATA_ATIVACAO
FROM TB_COMPETENCIA_ATIVA
WHERE ST_ATIVA = 'S'
ORDER BY DT_ATIVACAO DESC;

-- Verificar também todas as competências disponíveis
SELECT 
    DT_COMPETENCIA AS COMPETENCIA,
    ST_ATIVA AS STATUS,
    DT_ATIVACAO AS DATA_ATIVACAO
FROM TB_COMPETENCIA_ATIVA
ORDER BY DT_COMPETENCIA DESC;

