-- Script para verificar permissões na tabela TB_PROCOMUNS
-- Execute este script para verificar se o usuário SYSDBA tem permissões de INSERT/UPDATE/DELETE

-- 1. Verificar permissões do usuário SYSDBA na tabela TB_PROCOMUNS
SELECT 
    RF.RDB$RELATION_NAME AS TABELA,
    RF.RDB$USER AS USUARIO,
    RF.RDB$PRIVILEGE AS PRIVILEGIO,
    CASE RF.RDB$PRIVILEGE
        WHEN 'S' THEN 'SELECT'
        WHEN 'I' THEN 'INSERT'
        WHEN 'U' THEN 'UPDATE'
        WHEN 'D' THEN 'DELETE'
        WHEN 'R' THEN 'REFERENCES'
        WHEN 'X' THEN 'EXECUTE'
        ELSE 'OUTRO'
    END AS PRIVILEGIO_DESCRICAO
FROM RDB$USER_PRIVILEGES RF
WHERE RF.RDB$RELATION_NAME = 'TB_PROCOMUNS'
  AND RF.RDB$USER = 'SYSDBA'
ORDER BY RF.RDB$PRIVILEGE;

-- 2. Verificar se a tabela existe e está acessível
SELECT 
    COUNT(*) AS TABELA_EXISTE
FROM RDB$RELATIONS
WHERE RDB$RELATION_NAME = 'TB_PROCOMUNS'
  AND RDB$SYSTEM_FLAG = 0;

-- 3. Teste de leitura (SELECT) - deve funcionar sempre
SELECT COUNT(*) AS TOTAL_REGISTROS FROM TB_PROCOMUNS;

-- 4. Verificar estrutura da tabela
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    IIF(RF.RDB$NULL_FLAG IS NULL, 'SIM', 'NÃO') AS PERMITE_NULL
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_PROCOMUNS'
ORDER BY RF.RDB$FIELD_POSITION;

