-- Script para criar TB_COMPETENCIA_ATIVA e registrar competência 202510
-- Execute este script no banco de dados Firebird

-- 1. Verificar se a tabela TB_COMPETENCIA_ATIVA existe
SELECT 
    'VERIFICACAO: Tabela TB_COMPETENCIA_ATIVA existe?' AS INFO
FROM RDB$DATABASE
WHERE 1=0;

SELECT COUNT(*) AS existe
FROM RDB$RELATIONS
WHERE RDB$RELATION_NAME = 'TB_COMPETENCIA_ATIVA'
  AND RDB$SYSTEM_FLAG = 0;

-- 2. Criar tabela TB_COMPETENCIA_ATIVA se não existir
-- Execute apenas se a tabela não existir (existe = 0)
CREATE TABLE TB_COMPETENCIA_ATIVA (
    DT_COMPETENCIA VARCHAR(6) NOT NULL PRIMARY KEY,
    DT_ATIVACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ST_ATIVA CHAR(1) DEFAULT 'N'
);

-- 3. Registrar competência 202510 (se não existir)
INSERT INTO TB_COMPETENCIA_ATIVA (DT_COMPETENCIA, ST_ATIVA, DT_ATIVACAO)
SELECT '202510', 'N', CURRENT_TIMESTAMP
FROM RDB$DATABASE
WHERE NOT EXISTS (
    SELECT 1 FROM TB_COMPETENCIA_ATIVA WHERE DT_COMPETENCIA = '202510'
);

-- 4. Verificar se foi registrada
SELECT 
    'VERIFICACAO: Competencia 202510 registrada?' AS INFO
FROM RDB$DATABASE
WHERE 1=0;

SELECT DT_COMPETENCIA, ST_ATIVA, DT_ATIVACAO
FROM TB_COMPETENCIA_ATIVA
WHERE DT_COMPETENCIA = '202510';

-- 5. Listar todas as competências registradas
SELECT 
    'LISTAGEM: Todas as competencias em TB_COMPETENCIA_ATIVA' AS INFO
FROM RDB$DATABASE
WHERE 1=0;

SELECT DT_COMPETENCIA, ST_ATIVA, DT_ATIVACAO
FROM TB_COMPETENCIA_ATIVA
ORDER BY DT_COMPETENCIA DESC;

