-- Buscar tabelas relacionadas a Instrumento de Registro
-- Tentando vários termos possíveis

-- 1. Buscar tabelas com INSTRUMENTO
SELECT RDB$RELATION_NAME
FROM RDB$RELATIONS
WHERE RDB$SYSTEM_FLAG = 0
  AND (UPPER(RDB$RELATION_NAME) CONTAINING 'INSTRUMENTO'
   OR UPPER(RDB$RELATION_NAME) CONTAINING 'REGISTRO'
   OR UPPER(RDB$RELATION_NAME) CONTAINING 'INSTRUM')
ORDER BY RDB$RELATION_NAME;
