-- Buscar exemplos mais detalhados de procedimentos com tipo de leito
-- Agrupa por procedimento para mostrar todos os tipos de leito associados

SELECT FIRST 10
    pr.CO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS VARCHAR(100)) AS NOME_PROCEDIMENTO,
    tl.CO_TIPO_LEITO,
    CAST(tl.NO_TIPO_LEITO AS VARCHAR(60)) AS NOME_TIPO_LEITO
FROM TB_PROCEDIMENTO pr
INNER JOIN RL_PROCEDIMENTO_LEITO pl ON pr.CO_PROCEDIMENTO = pl.CO_PROCEDIMENTO
INNER JOIN TB_TIPO_LEITO tl ON pl.CO_TIPO_LEITO = tl.CO_TIPO_LEITO
WHERE pr.DT_COMPETENCIA = '201108'
  AND pl.DT_COMPETENCIA = '201108'
  AND tl.DT_COMPETENCIA = '201108'
ORDER BY pr.CO_PROCEDIMENTO, tl.CO_TIPO_LEITO;
