-- Script para testar query de relatório por Forma de Organização
-- Objetivo: Verificar se conseguimos buscar procedimentos por forma de organização

-- Exemplo 1: Buscar procedimentos da forma de organização '01' na competência '202401'
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE pr.CO_FORMA_ORGANIZACAO = '01'
  AND pr.DT_COMPETENCIA = '202401'
  AND pr.VL_SP > 0
ORDER BY pr.CO_PROCEDIMENTO;

-- Exemplo 2: Buscar procedimentos incluindo SP zerado
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE pr.CO_FORMA_ORGANIZACAO = '01'
  AND pr.DT_COMPETENCIA = '202401'
ORDER BY pr.VL_SP DESC;

-- Exemplo 3: Contar total de procedimentos por forma de organização
SELECT 
    pr.CO_FORMA_ORGANIZACAO AS CODIGO_FORMA_ORG,
    COUNT(*) AS TOTAL_PROCEDIMENTOS,
    COUNT(CASE WHEN pr.VL_SP > 0 THEN 1 END) AS TOTAL_COM_SP_MAIOR_ZERO
FROM TB_PROCEDIMENTO pr
WHERE pr.DT_COMPETENCIA = '202401'
GROUP BY pr.CO_FORMA_ORGANIZACAO
ORDER BY pr.CO_FORMA_ORGANIZACAO;

