-- Script para testar query de relatório por Procedimento específico
-- Objetivo: Verificar se conseguimos buscar um procedimento específico

-- Exemplo 1: Buscar procedimento específico por código
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE pr.CO_PROCEDIMENTO = '0301100012'
  AND pr.DT_COMPETENCIA = '202401'
  AND pr.VL_SP > 0;

-- Exemplo 2: Buscar procedimento incluindo SP zerado
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE pr.CO_PROCEDIMENTO = '0301100012'
  AND pr.DT_COMPETENCIA = '202401';

-- Exemplo 3: Buscar procedimentos por parte do código (LIKE)
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE pr.CO_PROCEDIMENTO CONTAINING '0301'
  AND pr.DT_COMPETENCIA = '202401'
  AND pr.VL_SP > 0
ORDER BY pr.CO_PROCEDIMENTO;

-- Exemplo 4: Buscar procedimentos por parte do nome
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE UPPER(CAST(pr.NO_PROCEDIMENTO AS VARCHAR(250))) CONTAINING 'ADMINISTRACAO'
  AND pr.DT_COMPETENCIA = '202401'
  AND pr.VL_SP > 0
ORDER BY pr.NO_PROCEDIMENTO;

