-- Script para testar query de relatório por Sub-grupo
-- Competência: 202006

-- Exemplo 1: Buscar procedimentos do sub-grupo '0101' na competência '202006' (com SP > 0)
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 4) = '0101'
  AND pr.DT_COMPETENCIA = '202006'
  AND pr.VL_SP > 0
ORDER BY pr.CO_PROCEDIMENTO
ROWS 1 TO 10;

-- Exemplo 2: Contar total de procedimentos do sub-grupo '0101'
SELECT 
    COUNT(*) AS TOTAL_PROCEDIMENTOS,
    COUNT(CASE WHEN pr.VL_SP > 0 THEN 1 END) AS TOTAL_COM_SP_MAIOR_ZERO,
    COUNT(CASE WHEN pr.VL_SP = 0 OR pr.VL_SP IS NULL THEN 1 END) AS TOTAL_COM_SP_ZERADO
FROM TB_PROCEDIMENTO pr
WHERE SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 4) = '0101'
  AND pr.DT_COMPETENCIA = '202006';

-- Exemplo 3: Listar sub-grupos disponíveis do grupo '01'
SELECT DISTINCT
    SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 2) AS CODIGO_GRUPO,
    SUBSTRING(pr.CO_PROCEDIMENTO FROM 3 FOR 2) AS CODIGO_SUBGRUPO,
    SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 4) AS CODIGO_COMPLETO_SUBGRUPO,
    COUNT(*) AS TOTAL_PROCEDIMENTOS
FROM TB_PROCEDIMENTO pr
WHERE SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 2) = '01'
  AND pr.DT_COMPETENCIA = '202006'
GROUP BY SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 2), SUBSTRING(pr.CO_PROCEDIMENTO FROM 3 FOR 2), SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 4)
ORDER BY SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 4)
ROWS 1 TO 10;

