-- Script para testar query de relatório por Procedimento específico
-- Competência: 202006

-- Exemplo 1: Buscar procedimento específico por código completo
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE pr.CO_PROCEDIMENTO = '0301100012'
  AND pr.DT_COMPETENCIA = '202006';

-- Exemplo 2: Buscar procedimentos por parte do código (LIKE/CONTAINING)
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE pr.CO_PROCEDIMENTO CONTAINING '0301'
  AND pr.DT_COMPETENCIA = '202006'
  AND pr.VL_SP > 0
ORDER BY pr.CO_PROCEDIMENTO
ROWS 1 TO 10;

-- Exemplo 3: Buscar procedimentos por parte do nome
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE UPPER(CAST(pr.NO_PROCEDIMENTO AS VARCHAR(250))) CONTAINING 'ADMINISTRACAO'
  AND pr.DT_COMPETENCIA = '202006'
  AND pr.VL_SP > 0
ORDER BY pr.NO_PROCEDIMENTO
ROWS 1 TO 10;

-- Exemplo 4: Testar ordenações diferentes
-- Ordenar por código
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP
FROM TB_PROCEDIMENTO pr
WHERE SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 2) = '01'
  AND pr.DT_COMPETENCIA = '202006'
  AND pr.VL_SP > 0
ORDER BY pr.CO_PROCEDIMENTO
ROWS 1 TO 5;

-- Ordenar por nome
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP
FROM TB_PROCEDIMENTO pr
WHERE SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 2) = '01'
  AND pr.DT_COMPETENCIA = '202006'
  AND pr.VL_SP > 0
ORDER BY pr.NO_PROCEDIMENTO
ROWS 1 TO 5;

-- Ordenar por valor SP (decrescente)
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO_PROCEDIMENTO,
    pr.NO_PROCEDIMENTO AS NOME_PROCEDIMENTO,
    pr.VL_SP AS VALOR_SP
FROM TB_PROCEDIMENTO pr
WHERE SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 2) = '01'
  AND pr.DT_COMPETENCIA = '202006'
  AND pr.VL_SP > 0
ORDER BY pr.VL_SP DESC
ROWS 1 TO 5;

