-- Script para verificar como procedimentos se relacionam com grupos, sub-grupos e formas de organização
-- Objetivo: Entender a estrutura de relacionamento

-- 1. Verificar estrutura de alguns procedimentos de exemplo
SELECT 
    pr.CO_PROCEDIMENTO AS CODIGO,
    SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 2) AS POSSIVEL_GRUPO,
    SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 4) AS POSSIVEL_SUBGRUPO,
    SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 6) AS POSSIVEL_FORMA_ORG,
    pr.DT_COMPETENCIA AS COMPETENCIA
FROM TB_PROCEDIMENTO pr
WHERE pr.DT_COMPETENCIA = '202401'
ORDER BY pr.CO_PROCEDIMENTO
ROWS 1 TO 20;

-- 2. Verificar se há tabelas intermediárias de relacionamento
SELECT 
    RF.RDB$RELATION_NAME AS TABELA
FROM RDB$RELATIONS RF
WHERE RF.RDB$SYSTEM_FLAG = 0
  AND RF.RDB$RELATION_TYPE = 0
  AND (
    UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'PROCEDIMENTO'
    AND (
      UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'GRUPO'
      OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'SUB'
      OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'FORMA'
      OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'ORGANIZACAO'
    )
  )
ORDER BY RF.RDB$RELATION_NAME;

-- 3. Verificar estrutura de TB_GRUPO para ver se há relacionamento reverso
SELECT 
    g.CO_GRUPO AS CODIGO_GRUPO,
    CAST(g.NO_GRUPO AS BLOB) AS NO_GRUPO_BLOB,
    g.NO_GRUPO AS NOME_GRUPO,
    g.DT_COMPETENCIA AS COMPETENCIA
FROM TB_GRUPO g
WHERE g.DT_COMPETENCIA = '202401'
ORDER BY g.CO_GRUPO
ROWS 1 TO 10;

-- 4. Verificar se o código do procedimento começa com o código do grupo
SELECT 
    g.CO_GRUPO AS CODIGO_GRUPO,
    COUNT(DISTINCT pr.CO_PROCEDIMENTO) AS TOTAL_PROCEDIMENTOS
FROM TB_GRUPO g
LEFT JOIN TB_PROCEDIMENTO pr ON SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 2) = g.CO_GRUPO
  AND pr.DT_COMPETENCIA = g.DT_COMPETENCIA
WHERE g.DT_COMPETENCIA = '202401'
GROUP BY g.CO_GRUPO
ORDER BY g.CO_GRUPO;

-- 5. Verificar estrutura de TB_SUB_GRUPO (com underscore)
SELECT 
    sg.CO_SUB_GRUPO AS CODIGO_SUBGRUPO,
    sg.CO_GRUPO AS CODIGO_GRUPO,
    CAST(sg.NO_SUB_GRUPO AS BLOB) AS NO_SUB_GRUPO_BLOB,
    sg.NO_SUB_GRUPO AS NOME_SUBGRUPO,
    sg.DT_COMPETENCIA AS COMPETENCIA
FROM TB_SUB_GRUPO sg
WHERE sg.DT_COMPETENCIA = '202401'
ORDER BY sg.CO_GRUPO, sg.CO_SUB_GRUPO
ROWS 1 TO 10;

-- 6. Verificar se o código do procedimento começa com o código do sub-grupo
SELECT 
    sg.CO_GRUPO AS CODIGO_GRUPO,
    sg.CO_SUB_GRUPO AS CODIGO_SUBGRUPO,
    COUNT(DISTINCT pr.CO_PROCEDIMENTO) AS TOTAL_PROCEDIMENTOS
FROM TB_SUB_GRUPO sg
LEFT JOIN TB_PROCEDIMENTO pr ON SUBSTRING(pr.CO_PROCEDIMENTO FROM 1 FOR 4) = (sg.CO_GRUPO || sg.CO_SUB_GRUPO)
  AND pr.DT_COMPETENCIA = sg.DT_COMPETENCIA
WHERE sg.DT_COMPETENCIA = '202401'
GROUP BY sg.CO_GRUPO, sg.CO_SUB_GRUPO
ORDER BY sg.CO_GRUPO, sg.CO_SUB_GRUPO;

