-- Verificar estrutura e dados das tabelas de Instrumento de Registro

-- 1. Estrutura de TB_REGISTRO
SELECT FIRST 1 * FROM TB_REGISTRO;

-- 2. Estrutura de RL_PROCEDIMENTO_REGISTRO  
SELECT FIRST 1 * FROM RL_PROCEDIMENTO_REGISTRO;

-- 3. Contar registros
SELECT 'TB_REGISTRO' AS TABELA, COUNT(*) AS TOTAL FROM TB_REGISTRO
UNION ALL
SELECT 'RL_PROCEDIMENTO_REGISTRO', COUNT(*) FROM RL_PROCEDIMENTO_REGISTRO;

-- 4. Exemplos de dados em TB_REGISTRO
SELECT FIRST 10 * FROM TB_REGISTRO ORDER BY CO_REGISTRO;

-- 5. Exemplo de relacionamento
SELECT FIRST 5
    pr.CO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS VARCHAR(100)) AS NOME_PROCEDIMENTO,
    reg.CO_REGISTRO,
    CAST(reg.NO_REGISTRO AS VARCHAR(100)) AS NOME_REGISTRO
FROM TB_PROCEDIMENTO pr
INNER JOIN RL_PROCEDIMENTO_REGISTRO prreg ON pr.CO_PROCEDIMENTO = prreg.CO_PROCEDIMENTO
INNER JOIN TB_REGISTRO reg ON prreg.CO_REGISTRO = reg.CO_REGISTRO
WHERE pr.DT_COMPETENCIA = '201108'
  AND prreg.DT_COMPETENCIA = '201108'
ORDER BY pr.CO_PROCEDIMENTO;
