-- Script para verificar se existem tabelas relacionadas a procedimentos comuns ou observações
-- Execute este script no banco de dados para verificar

-- 1. Listar TODAS as tabelas do banco
SELECT 
    RF.RDB$RELATION_NAME AS TABELA
FROM RDB$RELATIONS RF
WHERE RF.RDB$SYSTEM_FLAG = 0
  AND RF.RDB$RELATION_TYPE = 0
ORDER BY RF.RDB$RELATION_NAME;

-- 2. Procurar por tabelas que possam estar relacionadas a procedimentos comuns
-- Procurar por nomes que contenham: COMUM, OBSERVACAO, FAVORITO, USUARIO, PERSONALIZADO
SELECT 
    RF.RDB$RELATION_NAME AS TABELA
FROM RDB$RELATIONS RF
WHERE RF.RDB$SYSTEM_FLAG = 0
  AND RF.RDB$RELATION_TYPE = 0
  AND (
    UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'COMUM'
    OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'OBSERVACAO'
    OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'FAVORITO'
    OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'USUARIO'
    OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'PERSONALIZADO'
    OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'NOTA'
    OR UPPER(TRIM(RF.RDB$RELATION_NAME)) CONTAINING 'ANOTACAO'
  )
ORDER BY RF.RDB$RELATION_NAME;

-- 3. Verificar se há campos de observação em TB_PROCEDIMENTO
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO
FROM RDB$RELATION_FIELDS RF
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
  AND (
    UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'OBSERVACAO'
    OR UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'NOTA'
    OR UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'COMUM'
    OR UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'FAVORITO'
  )
ORDER BY RF.RDB$FIELD_NAME;

-- 4. Verificar estrutura completa de TB_PROCEDIMENTO para ver todos os campos
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 27 THEN 'DOUBLE PRECISION'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
ORDER BY RF.RDB$FIELD_POSITION;

