-- Verificar dados de Tipo de Leito
SET LIST ON;

SELECT COUNT(*) AS TOTAL_TIPOS_LEITO
FROM TB_TIPO_LEITO;

SELECT FIRST 10
    CO_TIPO_LEITO,
    NO_TIPO_LEITO,
    DT_COMPETENCIA
FROM TB_TIPO_LEITO;

SELECT COUNT(*) AS TOTAL_RELACIONAMENTOS
FROM RL_PROCEDIMENTO_LEITO;

SELECT FIRST 10
    CO_PROCEDIMENTO,
    CO_TIPO_LEITO,
    DT_COMPETENCIA
FROM RL_PROCEDIMENTO_LEITO;
