-- Script para verificar campos de TB_PROCEDIMENTO relacionados a grupos, sub-grupos e formas de organização
-- Objetivo: Identificar os nomes corretos dos campos

-- 1. Listar TODOS os campos de TB_PROCEDIMENTO
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 27 THEN 'DOUBLE PRECISION'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
ORDER BY RF.RDB$FIELD_POSITION;

-- 2. Procurar campos que contenham GRUPO, SUB, FORMA, ORGANIZACAO
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM
FROM RDB$RELATION_FIELDS RF
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
  AND (
    UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'GRUPO'
    OR UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'SUB'
    OR UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'FORMA'
    OR UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'ORGANIZACAO'
    OR UPPER(TRIM(RF.RDB$FIELD_NAME)) CONTAINING 'ORGANIZ'
  )
ORDER BY RF.RDB$FIELD_NAME;

