-- Script para verificar estrutura de dados necessária para relatórios
-- Objetivo: Identificar tabelas e campos relacionados a grupos, sub-grupos, formas de organização e procedimentos

-- 1. Verificar estrutura da tabela TB_GRUPO
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    IIF(RF.RDB$NULL_FLAG IS NULL, 'SIM', 'NÃO') AS PERMITE_NULL
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_GRUPO'
ORDER BY RF.RDB$FIELD_POSITION;

-- 2. Verificar estrutura da tabela TB_SUBGRUPO
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    IIF(RF.RDB$NULL_FLAG IS NULL, 'SIM', 'NÃO') AS PERMITE_NULL
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_SUBGRUPO'
ORDER BY RF.RDB$FIELD_POSITION;

-- 3. Verificar estrutura da tabela TB_FORMA_ORGANIZACAO
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    IIF(RF.RDB$NULL_FLAG IS NULL, 'SIM', 'NÃO') AS PERMITE_NULL
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_FORMA_ORGANIZACAO'
ORDER BY RF.RDB$FIELD_POSITION;

-- 4. Verificar campos relevantes de TB_PROCEDIMENTO para relatórios
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 27 THEN 'DOUBLE PRECISION'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    IIF(RF.RDB$NULL_FLAG IS NULL, 'SIM', 'NÃO') AS PERMITE_NULL
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
  AND (
    RF.RDB$FIELD_NAME CONTAINING 'CO_GRUPO'
    OR RF.RDB$FIELD_NAME CONTAINING 'CO_SUBGRUPO'
    OR RF.RDB$FIELD_NAME CONTAINING 'CO_FORMA_ORGANIZACAO'
    OR RF.RDB$FIELD_NAME CONTAINING 'CO_PROCEDIMENTO'
    OR RF.RDB$FIELD_NAME CONTAINING 'NO_PROCEDIMENTO'
    OR RF.RDB$FIELD_NAME CONTAINING 'VL_SP'
    OR RF.RDB$FIELD_NAME CONTAINING 'DT_COMPETENCIA'
  )
ORDER BY RF.RDB$FIELD_POSITION;

-- 5. Verificar relacionamentos (chaves estrangeiras lógicas)
-- CO_GRUPO em TB_PROCEDIMENTO
SELECT COUNT(*) AS TOTAL_PROCEDIMENTOS_COM_GRUPO
FROM TB_PROCEDIMENTO
WHERE CO_GRUPO IS NOT NULL;

-- CO_SUBGRUPO em TB_PROCEDIMENTO
SELECT COUNT(*) AS TOTAL_PROCEDIMENTOS_COM_SUBGRUPO
FROM TB_PROCEDIMENTO
WHERE CO_SUBGRUPO IS NOT NULL;

-- CO_FORMA_ORGANIZACAO em TB_PROCEDIMENTO
SELECT COUNT(*) AS TOTAL_PROCEDIMENTOS_COM_FORMA_ORG
FROM TB_PROCEDIMENTO
WHERE CO_FORMA_ORGANIZACAO IS NOT NULL;

