-- Script para verificar se os campos VL_TA e VL_TH existem na tabela TB_PROCEDIMENTO
-- Execute este script no banco Firebird para verificar

-- Método 1: Tentar selecionar os campos (vai dar erro se não existirem)
-- Descomente as linhas abaixo para testar:

-- SELECT VL_TA, VL_TH FROM TB_PROCEDIMENTO WHERE ROW_COUNT = 0;

-- Método 2: Verificar na tabela de metadados do Firebird
-- Firebird armazena informações sobre colunas em RDB$RELATION_FIELDS

SELECT 
    RF.RDB$FIELD_NAME AS NOME_COLUNA,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    RF.RDB$NULL_FLAG AS PERMITE_NULL,
    F.RDB$FIELD_TYPE AS TIPO_CAMPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    F.RDB$FIELD_SCALE AS ESCALA
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
  AND (RF.RDB$FIELD_NAME = 'VL_TA' OR RF.RDB$FIELD_NAME = 'VL_TH')
ORDER BY RF.RDB$FIELD_NAME;

-- Método 3: Listar TODAS as colunas da tabela TB_PROCEDIMENTO para ver o que existe
SELECT 
    RF.RDB$FIELD_NAME AS NOME_COLUNA,
    CASE 
        WHEN RF.RDB$NULL_FLAG IS NULL THEN 'SIM'
        ELSE 'NÃO'
    END AS PERMITE_NULL,
    F.RDB$FIELD_TYPE AS TIPO_CAMPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    F.RDB$FIELD_SCALE AS ESCALA
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
  AND RF.RDB$FIELD_NAME LIKE 'VL_%'
ORDER BY RF.RDB$FIELD_NAME;

-- Método 4: Verificar se há dados nesses campos (se existirem)
-- Descomente se os campos existirem:

-- SELECT 
--     COUNT(*) AS TOTAL_REGISTROS,
--     COUNT(VL_TA) AS REGISTROS_COM_VL_TA,
--     COUNT(VL_TH) AS REGISTROS_COM_VL_TH,
--     SUM(CASE WHEN VL_TA IS NOT NULL THEN 1 ELSE 0 END) AS NAO_NULL_VL_TA,
--     SUM(CASE WHEN VL_TH IS NOT NULL THEN 1 ELSE 0 END) AS NAO_NULL_VL_TH
-- FROM TB_PROCEDIMENTO;

