-- Script para verificar o charset do banco Firebird
-- Execute no ISQL ou Flamerobin

-- Verificar o charset padrão do banco
SELECT RDB$CHARACTER_SET_NAME 
FROM RDB$DATABASE;

-- Verificar os charsets disponíveis
SELECT RDB$CHARACTER_SET_NAME, RDB$BYTES_PER_CHARACTER
FROM RDB$CHARACTER_SETS
WHERE RDB$CHARACTER_SET_NAME IS NOT NULL
ORDER BY RDB$CHARACTER_SET_NAME;

-- Verificar o charset de um campo específico (exemplo com TB_PROCEDIMENTO.NO_PROCEDIMENTO)
SELECT 
    RF.RDB$FIELD_NAME,
    CS.RDB$CHARACTER_SET_NAME,
    CS.RDB$BYTES_PER_CHARACTER
FROM RDB$RELATION_FIELDS RF
JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
LEFT JOIN RDB$CHARACTER_SETS CS ON F.RDB$CHARACTER_SET_ID = CS.RDB$CHARACTER_SET_ID
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
  AND RF.RDB$FIELD_NAME = 'NO_PROCEDIMENTO';

-- Verificar todos os campos da tabela TB_PROCEDIMENTO e seus charsets
SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    CS.RDB$CHARACTER_SET_NAME AS CHARSET,
    RF.RDB$FIELD_TYPE AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO
FROM RDB$RELATION_FIELDS RF
JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
LEFT JOIN RDB$CHARACTER_SETS CS ON F.RDB$CHARACTER_SET_ID = CS.RDB$CHARACTER_SET_ID
WHERE RF.RDB$RELATION_NAME = 'TB_PROCEDIMENTO'
ORDER BY RF.RDB$FIELD_POSITION;

-- Verificar um registro de teste para ver como os dados estão armazenados
SELECT FIRST 1
    CO_PROCEDIMENTO,
    NO_PROCEDIMENTO,
    CAST(NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BYTES
FROM TB_PROCEDIMENTO
WHERE NO_PROCEDIMENTO CONTAINING 'ORIENTA'
   OR NO_PROCEDIMENTO CONTAINING 'ATEN';


