-- Script para verificar duplicatas restantes
SELECT 
    'PROGRESSO' AS STATUS,
    COUNT(*) AS GRUPOS_DUPLICATAS_RESTANTES,
    (SELECT COUNT(*) FROM RL_PROCEDIMENTO_CID WHERE DT_COMPETENCIA = '202510') AS TOTAL_REGISTROS
FROM (
    SELECT CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
    FROM RL_PROCEDIMENTO_CID
    WHERE DT_COMPETENCIA = '202510'
    GROUP BY CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
    HAVING COUNT(*) > 1
);

