-- Script para executar no servidor - Limpa 10 duplicatas por vez
-- PRIMEIRO lista os registros, DEPOIS remove
-- Mostra logs detalhados de cada registro removido

SET TERM ^ ;

-- 1. Listar registros que SERÃO removidos (com detalhes completos)
SELECT 
    '>>> REMOVENDO' AS ACAO,
    pc.INDICE,
    pc.CO_CID,
    pc.CO_PROCEDIMENTO,
    pc.DT_COMPETENCIA,
    SUBSTRING(pc.NO_CID FROM 1 FOR 60) AS NO_CID
FROM RL_PROCEDIMENTO_CID pc
WHERE pc.DT_COMPETENCIA = '202510'
  AND EXISTS (
      SELECT 1
      FROM RL_PROCEDIMENTO_CID pc2
      WHERE pc2.DT_COMPETENCIA = '202510'
        AND pc2.CO_CID = pc.CO_CID
        AND pc2.CO_PROCEDIMENTO = pc.CO_PROCEDIMENTO
        AND pc2.DT_COMPETENCIA = pc.DT_COMPETENCIA
      GROUP BY pc2.CO_CID, pc2.CO_PROCEDIMENTO, pc2.DT_COMPETENCIA
      HAVING COUNT(*) > 1
  )
  AND pc.INDICE <> (
      SELECT MIN(INDICE)
      FROM RL_PROCEDIMENTO_CID pc3
      WHERE pc3.DT_COMPETENCIA = '202510'
        AND pc3.CO_CID = pc.CO_CID
        AND pc3.CO_PROCEDIMENTO = pc.CO_PROCEDIMENTO
        AND pc3.DT_COMPETENCIA = pc.DT_COMPETENCIA
  )
ORDER BY pc.INDICE
ROWS 1 TO 10
^

SET TERM ; ^

-- 2. Remover os registros (mesmos critérios)
DELETE FROM RL_PROCEDIMENTO_CID
WHERE DT_COMPETENCIA = '202510'
  AND EXISTS (
      SELECT 1
      FROM RL_PROCEDIMENTO_CID pc2
      WHERE pc2.DT_COMPETENCIA = '202510'
        AND pc2.CO_CID = RL_PROCEDIMENTO_CID.CO_CID
        AND pc2.CO_PROCEDIMENTO = RL_PROCEDIMENTO_CID.CO_PROCEDIMENTO
        AND pc2.DT_COMPETENCIA = RL_PROCEDIMENTO_CID.DT_COMPETENCIA
      GROUP BY pc2.CO_CID, pc2.CO_PROCEDIMENTO, pc2.DT_COMPETENCIA
      HAVING COUNT(*) > 1
  )
  AND INDICE <> (
      SELECT MIN(INDICE)
      FROM RL_PROCEDIMENTO_CID pc3
      WHERE pc3.DT_COMPETENCIA = '202510'
        AND pc3.CO_CID = RL_PROCEDIMENTO_CID.CO_CID
        AND pc3.CO_PROCEDIMENTO = RL_PROCEDIMENTO_CID.CO_PROCEDIMENTO
        AND pc3.DT_COMPETENCIA = RL_PROCEDIMENTO_CID.DT_COMPETENCIA
  )
  AND INDICE IN (
      SELECT FIRST 10 INDICE
      FROM RL_PROCEDIMENTO_CID pc4
      WHERE pc4.DT_COMPETENCIA = '202510'
        AND EXISTS (
            SELECT 1
            FROM RL_PROCEDIMENTO_CID pc5
            WHERE pc5.DT_COMPETENCIA = '202510'
              AND pc5.CO_CID = pc4.CO_CID
              AND pc5.CO_PROCEDIMENTO = pc4.CO_PROCEDIMENTO
              AND pc5.DT_COMPETENCIA = pc4.DT_COMPETENCIA
            GROUP BY pc5.CO_CID, pc5.CO_PROCEDIMENTO, pc5.DT_COMPETENCIA
            HAVING COUNT(*) > 1
        )
        AND pc4.INDICE <> (
            SELECT MIN(INDICE)
            FROM RL_PROCEDIMENTO_CID pc6
            WHERE pc6.DT_COMPETENCIA = '202510'
              AND pc6.CO_CID = pc4.CO_CID
              AND pc6.CO_PROCEDIMENTO = pc4.CO_PROCEDIMENTO
              AND pc6.DT_COMPETENCIA = pc4.DT_COMPETENCIA
        )
      ORDER BY pc4.INDICE
  );

-- 3. Verificar progresso
SELECT 
    'PROGRESSO' AS STATUS,
    COUNT(*) AS GRUPOS_DUPLICATAS_RESTANTES,
    (SELECT COUNT(*) FROM RL_PROCEDIMENTO_CID WHERE DT_COMPETENCIA = '202510') AS TOTAL_REGISTROS
FROM (
    SELECT CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
    FROM RL_PROCEDIMENTO_CID
    WHERE DT_COMPETENCIA = '202510'
    GROUP BY CO_CID, CO_PROCEDIMENTO, DT_COMPETENCIA
    HAVING COUNT(*) > 1
);

