-- Script: Buscar um procedimento que possui CID10 relacionado
-- Objetivo: Encontrar um procedimento com CID10 para teste

SELECT 
    pr.CO_PROCEDIMENTO,
    CAST(pr.NO_PROCEDIMENTO AS BLOB) AS NO_PROCEDIMENTO_BLOB,
    pr.NO_PROCEDIMENTO,
    pc.CO_CID,
    CAST(c.NO_CID AS BLOB) AS NO_CID_BLOB,
    c.NO_CID,
    pc.ST_PRINCIPAL,
    pc.DT_COMPETENCIA
FROM RL_PROCEDIMENTO_CID pc
INNER JOIN TB_PROCEDIMENTO pr ON pc.CO_PROCEDIMENTO = pr.CO_PROCEDIMENTO
INNER JOIN TB_CID c ON pc.CO_CID = c.CO_CID
WHERE pr.DT_COMPETENCIA = pc.DT_COMPETENCIA
ORDER BY pr.CO_PROCEDIMENTO
ROWS 5;

