-- Script: Buscar Campos em Tabelas por Termo
-- Objetivo: Encontrar campos que contenham um termo específico no nome
-- Uso: Substituir 'TERMO' pelo termo de busca (ex: CID, CBO, OBSERVACAO)
-- Útil para encontrar campos relacionados mesmo que a tabela não tenha o nome do termo

SELECT 
    RF.RDB$RELATION_NAME AS TABELA,
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 16 THEN 'BIGINT'
        WHEN F.RDB$FIELD_TYPE = 27 THEN 'DOUBLE PRECISION'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
JOIN RDB$RELATIONS R ON RF.RDB$RELATION_NAME = R.RDB$RELATION_NAME
WHERE R.RDB$SYSTEM_FLAG = 0
  AND R.RDB$RELATION_TYPE = 0
  AND RF.RDB$FIELD_NAME CONTAINING 'TERMO'
ORDER BY RF.RDB$RELATION_NAME, RF.RDB$FIELD_POSITION;

