-- Script: Buscar um procedimento que possui procedimentos compatíveis relacionados
-- Objetivo: Encontrar um procedimento com compatíveis para teste

SELECT 
    pc.CO_PROCEDIMENTO_PRINCIPAL,
    pr1.CO_PROCEDIMENTO AS PRINC_COD,
    CAST(pr1.NO_PROCEDIMENTO AS BLOB) AS PRINC_NOME_BLOB,
    pr1.NO_PROCEDIMENTO AS PRINC_NOME,
    pc.CO_PROCEDIMENTO_COMPATIVEL,
    pr2.CO_PROCEDIMENTO AS COMPAT_COD,
    CAST(pr2.NO_PROCEDIMENTO AS BLOB) AS COMPAT_NOME_BLOB,
    pr2.NO_PROCEDIMENTO AS COMPAT_NOME,
    pc.DT_COMPETENCIA,
    pc.TP_COMPATIBILIDADE,
    pc.QT_PERMITIDA
FROM RL_PROCEDIMENTO_COMPATIVEL pc
INNER JOIN TB_PROCEDIMENTO pr1 ON pc.CO_PROCEDIMENTO_PRINCIPAL = pr1.CO_PROCEDIMENTO
INNER JOIN TB_PROCEDIMENTO pr2 ON pc.CO_PROCEDIMENTO_COMPATIVEL = pr2.CO_PROCEDIMENTO
WHERE pr1.DT_COMPETENCIA = pc.DT_COMPETENCIA
  AND pr2.DT_COMPETENCIA = pc.DT_COMPETENCIA
ORDER BY pc.CO_PROCEDIMENTO_PRINCIPAL
ROWS 5;

