-- Script: Verificar Índices e Constraints de uma Tabela
-- Objetivo: Obter informações sobre chaves primárias, estrangeiras e índices
-- Uso: Substituir 'NOME_DA_TABELA' pelo nome da tabela a analisar

-- Chaves Primárias
SELECT 
    'PRIMARY KEY' AS TIPO_CONSTRAINT,
    I.RDB$INDEX_NAME AS NOME_INDICE,
    S.RDB$FIELD_NAME AS CAMPO,
    S.RDB$FIELD_POSITION AS POSICAO
FROM RDB$INDICES I
JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME = 'NOME_DA_TABELA'
  AND I.RDB$UNIQUE_FLAG = 1
ORDER BY I.RDB$INDEX_NAME, S.RDB$FIELD_POSITION;

-- Chaves Estrangeiras
SELECT 
    'FOREIGN KEY' AS TIPO_CONSTRAINT,
    RC.RDB$CONSTRAINT_NAME AS NOME_CONSTRAINT,
    S1.RDB$FIELD_NAME AS CAMPO_ORIGEM,
    I2.RDB$RELATION_NAME AS TABELA_DESTINO,
    S2.RDB$FIELD_NAME AS CAMPO_DESTINO
FROM RDB$RELATION_CONSTRAINTS RC
LEFT JOIN RDB$INDEX_SEGMENTS S1 ON RC.RDB$INDEX_NAME = S1.RDB$INDEX_NAME
LEFT JOIN RDB$REF_CONSTRAINTS REF ON RC.RDB$CONSTRAINT_NAME = REF.RDB$CONSTRAINT_NAME
LEFT JOIN RDB$RELATION_CONSTRAINTS RC2 ON REF.RDB$CONST_NAME_UQ = RC2.RDB$CONSTRAINT_NAME
LEFT JOIN RDB$INDICES I2 ON RC2.RDB$INDEX_NAME = I2.RDB$INDEX_NAME
LEFT JOIN RDB$INDEX_SEGMENTS S2 ON I2.RDB$INDEX_NAME = S2.RDB$INDEX_NAME
WHERE RC.RDB$RELATION_NAME = 'NOME_DA_TABELA'
  AND RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY RC.RDB$CONSTRAINT_NAME;

-- Índices Únicos
SELECT 
    'UNIQUE INDEX' AS TIPO_CONSTRAINT,
    I.RDB$INDEX_NAME AS NOME_INDICE,
    S.RDB$FIELD_NAME AS CAMPO,
    S.RDB$FIELD_POSITION AS POSICAO
FROM RDB$INDICES I
JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME = 'NOME_DA_TABELA'
  AND I.RDB$UNIQUE_FLAG = 1
  AND I.RDB$INDEX_NAME NOT IN (
      SELECT RC.RDB$INDEX_NAME 
      FROM RDB$RELATION_CONSTRAINTS RC 
      WHERE RC.RDB$RELATION_NAME = 'NOME_DA_TABELA' 
        AND RC.RDB$CONSTRAINT_TYPE = 'PRIMARY KEY'
  )
ORDER BY I.RDB$INDEX_NAME, S.RDB$FIELD_POSITION;

