-- Script: Verificar Estrutura Completa de uma Tabela
-- Objetivo: Obter estrutura completa de campos, tipos e constraints
-- Uso: Substituir 'NOME_DA_TABELA' pelo nome da tabela a analisar

SELECT 
    RF.RDB$FIELD_NAME AS CAMPO,
    RF.RDB$FIELD_SOURCE AS TIPO_ORIGEM,
    CASE 
        WHEN F.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN F.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN F.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN F.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN F.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN F.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN F.RDB$FIELD_TYPE = 16 THEN 'BIGINT'
        WHEN F.RDB$FIELD_TYPE = 27 THEN 'DOUBLE PRECISION'
        WHEN F.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN F.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN F.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'OUTRO'
    END AS TIPO,
    F.RDB$FIELD_LENGTH AS TAMANHO,
    CASE WHEN RF.RDB$NULL_FLAG = 1 THEN 'NOT NULL' ELSE 'NULL' END AS NULLABLE,
    RF.RDB$FIELD_POSITION AS POSICAO
FROM RDB$RELATION_FIELDS RF
LEFT JOIN RDB$FIELDS F ON RF.RDB$FIELD_SOURCE = F.RDB$FIELD_NAME
WHERE RF.RDB$RELATION_NAME = 'NOME_DA_TABELA'
ORDER BY RF.RDB$FIELD_POSITION;

